//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.24 at 11:56:54 AM IST 
//


package com.cnk.siapi.requestpojo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cnk.siapi.requestpojo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cnk.siapi.requestpojo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ }
     * 
     */
    public SightSeeingInterfaceRQ createSightSeeingInterfaceRQ() {
        return new SightSeeingInterfaceRQ();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody createSightSeeingInterfaceRQRequestBody() {
        return new SightSeeingInterfaceRQ.RequestBody();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapper() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQ() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfo() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Pricing }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Pricing createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoPricing() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Pricing();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Pricing.ParticipantCategory }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Pricing.ParticipantCategory createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoPricingParticipantCategory() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Pricing.ParticipantCategory();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Pricing.Summary }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Pricing.Summary createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoPricingSummary() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Pricing.Summary();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Pricing.Summary.TaxAmounts }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Pricing.Summary.TaxAmounts createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoPricingSummaryTaxAmounts() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Pricing.Summary.TaxAmounts();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Location }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Location createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoLocation() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Location();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Location.Address }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Location.Address createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoLocationAddress() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Location.Address();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.ParticipantInfo }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.ParticipantInfo createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoParticipantInfo() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.ParticipantInfo();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.ParticipantInfo.Category }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.ParticipantInfo.Category createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoParticipantInfoCategory() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.ParticipantInfo.Category();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.ParticipantInfo.Category.Contact }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.ParticipantInfo.Category.Contact createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoParticipantInfoCategoryContact() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.ParticipantInfo.Category.Contact();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoBasicInfo() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoBasicInfoTPAExtensions() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoBasicInfoTPAExtensionsActivityTPA() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA.TimeSlots }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA.TimeSlots createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoBasicInfoTPAExtensionsActivityTPATimeSlots() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA.TimeSlots();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.ContactDetail }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.ContactDetail createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQContactDetail() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.ContactDetail();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.ContactDetail.Address }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.ContactDetail.Address createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQContactDetailAddress() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.ContactDetail.Address();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.POS }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.POS createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQPOS() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.POS();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestHeader }
     * 
     */
    public SightSeeingInterfaceRQ.RequestHeader createSightSeeingInterfaceRQRequestHeader() {
        return new SightSeeingInterfaceRQ.RequestHeader();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestHeader.SupplierCredentialsList }
     * 
     */
    public SightSeeingInterfaceRQ.RequestHeader.SupplierCredentialsList createSightSeeingInterfaceRQRequestHeaderSupplierCredentialsList() {
        return new SightSeeingInterfaceRQ.RequestHeader.SupplierCredentialsList();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestHeader.SupplierCredentialsList.SupplierCredentials }
     * 
     */
    public SightSeeingInterfaceRQ.RequestHeader.SupplierCredentialsList.SupplierCredentials createSightSeeingInterfaceRQRequestHeaderSupplierCredentialsListSupplierCredentials() {
        return new SightSeeingInterfaceRQ.RequestHeader.SupplierCredentialsList.SupplierCredentials();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestHeader.SupplierCredentialsList.SupplierCredentials.Credentials }
     * 
     */
    public SightSeeingInterfaceRQ.RequestHeader.SupplierCredentialsList.SupplierCredentials.Credentials createSightSeeingInterfaceRQRequestHeaderSupplierCredentialsListSupplierCredentialsCredentials() {
        return new SightSeeingInterfaceRQ.RequestHeader.SupplierCredentialsList.SupplierCredentials.Credentials();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestHeader.SupplierCredentialsList.SupplierCredentials.Credentials.OperationURLs }
     * 
     */
    public SightSeeingInterfaceRQ.RequestHeader.SupplierCredentialsList.SupplierCredentials.Credentials.OperationURLs createSightSeeingInterfaceRQRequestHeaderSupplierCredentialsListSupplierCredentialsCredentialsOperationURLs() {
        return new SightSeeingInterfaceRQ.RequestHeader.SupplierCredentialsList.SupplierCredentials.Credentials.OperationURLs();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Schedule }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Schedule createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoSchedule() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Schedule();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.PickupDropoff }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.PickupDropoff createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoPickupDropoff() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.PickupDropoff();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Pricing.ParticipantCategory.Price }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Pricing.ParticipantCategory.Price createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoPricingParticipantCategoryPrice() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Pricing.ParticipantCategory.Price();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Pricing.Summary.TaxAmounts.TaxAmount }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Pricing.Summary.TaxAmounts.TaxAmount createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoPricingSummaryTaxAmountsTaxAmount() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Pricing.Summary.TaxAmounts.TaxAmount();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Location.Region }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Location.Region createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoLocationRegion() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Location.Region();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Location.Address.CountryName }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Location.Address.CountryName createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoLocationAddressCountryName() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.Location.Address.CountryName();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.ParticipantInfo.Category.Contact.PersonName }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.ParticipantInfo.Category.Contact.PersonName createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoParticipantInfoCategoryContactPersonName() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.ParticipantInfo.Category.Contact.PersonName();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.ParticipantInfo.Category.Contact.Telephone }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.ParticipantInfo.Category.Contact.Telephone createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoParticipantInfoCategoryContactTelephone() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.ParticipantInfo.Category.Contact.Telephone();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA.CancellationPolicy }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA.CancellationPolicy createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoBasicInfoTPAExtensionsActivityTPACancellationPolicy() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA.CancellationPolicy();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA.SupplierDetails }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA.SupplierDetails createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoBasicInfoTPAExtensionsActivityTPASupplierDetails() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA.SupplierDetails();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA.TourLanguage }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA.TourLanguage createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoBasicInfoTPAExtensionsActivityTPATourLanguage() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA.TourLanguage();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA.POS }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA.POS createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoBasicInfoTPAExtensionsActivityTPAPOS() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA.POS();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA.Addons }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA.Addons createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoBasicInfoTPAExtensionsActivityTPAAddons() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA.Addons();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA.TimeSlots.TimeSlot }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA.TimeSlots.TimeSlot createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQBookingInfoBasicInfoTPAExtensionsActivityTPATimeSlotsTimeSlot() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.BookingInfo.BasicInfo.TPAExtensions.ActivityTPA.TimeSlots.TimeSlot();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.ContactDetail.PersonName }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.ContactDetail.PersonName createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQContactDetailPersonName() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.ContactDetail.PersonName();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.ContactDetail.Telephone }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.ContactDetail.Telephone createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQContactDetailTelephone() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.ContactDetail.Telephone();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.ContactDetail.Address.CountryName }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.ContactDetail.Address.CountryName createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQContactDetailAddressCountryName() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.ContactDetail.Address.CountryName();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.POS.Source }
     * 
     */
    public SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.POS.Source createSightSeeingInterfaceRQRequestBodyOTATourActivityBookRQWrapperOTATourActivityBookRQPOSSource() {
        return new SightSeeingInterfaceRQ.RequestBody.OTATourActivityBookRQWrapper.OTATourActivityBookRQ.POS.Source();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestHeader.SupplierCredentialsList.SupplierCredentials.Credentials.Credential }
     * 
     */
    public SightSeeingInterfaceRQ.RequestHeader.SupplierCredentialsList.SupplierCredentials.Credentials.Credential createSightSeeingInterfaceRQRequestHeaderSupplierCredentialsListSupplierCredentialsCredentialsCredential() {
        return new SightSeeingInterfaceRQ.RequestHeader.SupplierCredentialsList.SupplierCredentials.Credentials.Credential();
    }

    /**
     * Create an instance of {@link SightSeeingInterfaceRQ.RequestHeader.SupplierCredentialsList.SupplierCredentials.Credentials.OperationURLs.OperationURL }
     * 
     */
    public SightSeeingInterfaceRQ.RequestHeader.SupplierCredentialsList.SupplierCredentials.Credentials.OperationURLs.OperationURL createSightSeeingInterfaceRQRequestHeaderSupplierCredentialsListSupplierCredentialsCredentialsOperationURLsOperationURL() {
        return new SightSeeingInterfaceRQ.RequestHeader.SupplierCredentialsList.SupplierCredentials.Credentials.OperationURLs.OperationURL();
    }

}
