//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.24 at 11:56:54 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.coxandkings.com/scota", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cnk.siapi.requestpojo;
