//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 04:47:25 PM IST 
//


package com.cnk.siapi.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responseHeader",
    "responseBody"
})
@XmlRootElement(name = "SightSeeingInterfaceRS")
public class BookRS {

    @XmlElement(name = "ResponseHeader", required = true)
    protected BookRS.ResponseHeader responseHeader;
    @XmlElement(name = "ResponseBody", required = true)
    protected BookRS.ResponseBody responseBody;

    
    public BookRS.ResponseHeader getResponseHeader() {
        return responseHeader;
    }

    
    public void setResponseHeader(BookRS.ResponseHeader value) {
        this.responseHeader = value;
    }

    
    public BookRS.ResponseBody getResponseBody() {
        return responseBody;
    }

    
    public void setResponseBody(BookRS.ResponseBody value) {
        this.responseBody = value;
    }


    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "otaTourActivityBookRSWrapper"
    })
    public static class ResponseBody {

        @XmlElement(name = "OTA_TourActivityBookRSWrapper", required = true)
        protected BookRS.ResponseBody.OTATourActivityBookRSWrapper otaTourActivityBookRSWrapper;

        
        public BookRS.ResponseBody.OTATourActivityBookRSWrapper getOTATourActivityBookRSWrapper() {
            return otaTourActivityBookRSWrapper;
        }

        
        public void setOTATourActivityBookRSWrapper(BookRS.ResponseBody.OTATourActivityBookRSWrapper value) {
            this.otaTourActivityBookRSWrapper = value;
        }


        
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "supplierID",
            "sequence",
            "otaTourActivityBookRS"
        })
        public static class OTATourActivityBookRSWrapper {

            @XmlElement(name = "SupplierID", required = true)
            protected String supplierID;
            @XmlElement(name = "Sequence")
            protected Integer sequence;
            @XmlElement(name = "OTA_TourActivityBookRS", required = true)
            protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS otaTourActivityBookRS;

            
            public String getSupplierID() {
                return supplierID;
            }

            
            public void setSupplierID(String value) {
                this.supplierID = value;
            }

            
            public Integer getSequence() {
                return sequence;
            }

            
            public void setSequence(Integer value) {
                this.sequence = value;
            }

            
            public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS getOTATourActivityBookRS() {
                return otaTourActivityBookRS;
            }

            
            public void setOTATourActivityBookRS(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS value) {
                this.otaTourActivityBookRS = value;
            }


            
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "success",
                "reservationDetails"
            })
            public static class OTATourActivityBookRS {

                @XmlElement(name = "Success", required = true)
                protected String success;
                @XmlElement(name = "ReservationDetails", required = true)
                protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails reservationDetails;

                
                public String getSuccess() {
                    return success;
                }

                
                public void setSuccess(String value) {
                    this.success = value;
                }

                
                public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails getReservationDetails() {
                    return reservationDetails;
                }

                
                public void setReservationDetails(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails value) {
                    this.reservationDetails = value;
                }


                
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "basicInfo",
                    "confirmation",
                    "participantInfo",
                    "schedule",
                    "location",
                    "extra",
                    "pickupDropoff",
                    "pricing",
                    "tpaExtensions"
                })
                public static class ReservationDetails {

                    @XmlElement(name = "BasicInfo", required = true)
                    protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo basicInfo;
                    @XmlElement(name = "Confirmation")
                    protected List<BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Confirmation> confirmation;
                    @XmlElement(name = "ParticipantInfo")
                    protected List<BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.ParticipantInfo> participantInfo;
                    @XmlElement(name = "Schedule", required = true)
                    protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Schedule schedule;
                    @XmlElement(name = "Location", required = true)
                    protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Location location;
                    @XmlElement(name = "Extra", required = true)
                    protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Extra extra;
                    @XmlElement(name = "PickupDropoff", required = true)
                    protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.PickupDropoff pickupDropoff;
                    @XmlElement(name = "Pricing", required = true)
                    protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Pricing pricing;
                    @XmlElement(name = "TPA_Extensions", required = true)
                    protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.TPAExtensions tpaExtensions;

                    
                    public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo getBasicInfo() {
                        return basicInfo;
                    }

                    
                    public void setBasicInfo(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo value) {
                        this.basicInfo = value;
                    }

                    
                    public List<BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Confirmation> getConfirmation() {
                        if (confirmation == null) {
                            confirmation = new ArrayList<BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Confirmation>();
                        }
                        return this.confirmation;
                    }

                    
                    public List<BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.ParticipantInfo> getParticipantInfo() {
                        if (participantInfo == null) {
                            participantInfo = new ArrayList<BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.ParticipantInfo>();
                        }
                        return this.participantInfo;
                    }

                    
                    public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Schedule getSchedule() {
                        return schedule;
                    }

                    
                    public void setSchedule(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Schedule value) {
                        this.schedule = value;
                    }

                    
                    public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Location getLocation() {
                        return location;
                    }

                    
                    public void setLocation(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Location value) {
                        this.location = value;
                    }

                    
                    public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Extra getExtra() {
                        return extra;
                    }

                    
                    public void setExtra(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Extra value) {
                        this.extra = value;
                    }

                    
                    public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.PickupDropoff getPickupDropoff() {
                        return pickupDropoff;
                    }

                    
                    public void setPickupDropoff(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.PickupDropoff value) {
                        this.pickupDropoff = value;
                    }

                    
                    public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Pricing getPricing() {
                        return pricing;
                    }

                    
                    public void setPricing(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Pricing value) {
                        this.pricing = value;
                    }

                    
                    public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.TPAExtensions getTPAExtensions() {
                        return tpaExtensions;
                    }

                    
                    public void setTPAExtensions(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.TPAExtensions value) {
                        this.tpaExtensions = value;
                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "tpaExtensions"
                    })
                    public static class BasicInfo {

                        @XmlElement(name = "TPA_Extensions", required = true)
                        protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo.TPAExtensions tpaExtensions;
                        @XmlAttribute(name = "SupplierProductCode")
                        protected Integer supplierProductCode;
                        @XmlAttribute(name = "Name")
                        protected String name;

                        
                        public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo.TPAExtensions getTPAExtensions() {
                            return tpaExtensions;
                        }

                        
                        public void setTPAExtensions(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo.TPAExtensions value) {
                            this.tpaExtensions = value;
                        }

                        
                        public Integer getSupplierProductCode() {
                            return supplierProductCode;
                        }

                        
                        public void setSupplierProductCode(Integer value) {
                            this.supplierProductCode = value;
                        }

                        
                        public String getName() {
                            return name;
                        }

                        
                        public void setName(String value) {
                            this.name = value;
                        }


                        
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "activityTPA"
                        })
                        public static class TPAExtensions {

                            @XmlElement(name = "Activity_TPA", required = true)
                            protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo.TPAExtensions.ActivityTPA activityTPA;

                            
                            public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo.TPAExtensions.ActivityTPA getActivityTPA() {
                                return activityTPA;
                            }

                            
                            public void setActivityTPA(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo.TPAExtensions.ActivityTPA value) {
                                this.activityTPA = value;
                            }


                            
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "shippingDetails",
                                "participant",
                                "supplierDetails",
                                "vouchers",
                                "answers"
                            })
                            public static class ActivityTPA {

                                @XmlElement(name = "Shipping_Details", required = true)
                                protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo.TPAExtensions.ActivityTPA.ShippingDetails shippingDetails;
                                @XmlElement(name = "Participant", required = true)
                                protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo.TPAExtensions.ActivityTPA.Participant participant;
                                @XmlElement(name = "Supplier_Details", required = true)
                                protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo.TPAExtensions.ActivityTPA.SupplierDetails supplierDetails;
                                @XmlElement(name = "Vouchers", required = true)
                                protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo.TPAExtensions.ActivityTPA.Vouchers vouchers;
                                @XmlElement(name = "Answers", required = true)
                                protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo.TPAExtensions.ActivityTPA.Answers answers;

                                
                                public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo.TPAExtensions.ActivityTPA.ShippingDetails getShippingDetails() {
                                    return shippingDetails;
                                }

                                
                                public void setShippingDetails(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo.TPAExtensions.ActivityTPA.ShippingDetails value) {
                                    this.shippingDetails = value;
                                }

                                
                                public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo.TPAExtensions.ActivityTPA.Participant getParticipant() {
                                    return participant;
                                }

                                
                                public void setParticipant(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo.TPAExtensions.ActivityTPA.Participant value) {
                                    this.participant = value;
                                }

                                
                                public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo.TPAExtensions.ActivityTPA.SupplierDetails getSupplierDetails() {
                                    return supplierDetails;
                                }

                                
                                public void setSupplierDetails(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo.TPAExtensions.ActivityTPA.SupplierDetails value) {
                                    this.supplierDetails = value;
                                }

                                
                                public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo.TPAExtensions.ActivityTPA.Vouchers getVouchers() {
                                    return vouchers;
                                }

                                
                                public void setVouchers(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo.TPAExtensions.ActivityTPA.Vouchers value) {
                                    this.vouchers = value;
                                }

                                
                                public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo.TPAExtensions.ActivityTPA.Answers getAnswers() {
                                    return answers;
                                }

                                
                                public void setAnswers(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.BasicInfo.TPAExtensions.ActivityTPA.Answers value) {
                                    this.answers = value;
                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "value"
                                })
                                public static class Answers {

                                    @XmlValue
                                    protected String value;
                                    @XmlAttribute(name = "available")
                                    protected String available;

                                    
                                    public String getValue() {
                                        return value;
                                    }

                                    
                                    public void setValue(String value) {
                                        this.value = value;
                                    }

                                    
                                    public String getAvailable() {
                                        return available;
                                    }

                                    
                                    public void setAvailable(String value) {
                                        this.available = value;
                                    }

                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "value"
                                })
                                public static class Participant {

                                    @XmlValue
                                    protected String value;
                                    @XmlAttribute(name = "available")
                                    protected String available;
                                    @XmlAttribute(name = "minAdultAge")
                                    protected String minAdultAge;
                                    @XmlAttribute(name = "maxAdultAge")
                                    protected String maxAdultAge;
                                    @XmlAttribute(name = "maxIndividuals")
                                    protected String maxIndividuals;
                                    @XmlAttribute(name = "maxChildren")
                                    protected String maxChildren;
                                    @XmlAttribute(name = "maxAdults")
                                    protected String maxAdults;
                                    @XmlAttribute(name = "maxChildAge")
                                    protected String maxChildAge;
                                    @XmlAttribute(name = "minChildAge")
                                    protected String minChildAge;

                                    
                                    public String getValue() {
                                        return value;
                                    }

                                    
                                    public void setValue(String value) {
                                        this.value = value;
                                    }

                                    
                                    public String getAvailable() {
                                        return available;
                                    }

                                    
                                    public void setAvailable(String value) {
                                        this.available = value;
                                    }

                                    
                                    public String getMinAdultAge() {
                                        return minAdultAge;
                                    }

                                    
                                    public void setMinAdultAge(String value) {
                                        this.minAdultAge = value;
                                    }

                                    
                                    public String getMaxAdultAge() {
                                        return maxAdultAge;
                                    }

                                    
                                    public void setMaxAdultAge(String value) {
                                        this.maxAdultAge = value;
                                    }

                                    
                                    public String getMaxIndividuals() {
                                        return maxIndividuals;
                                    }

                                    
                                    public void setMaxIndividuals(String value) {
                                        this.maxIndividuals = value;
                                    }

                                    
                                    public String getMaxChildren() {
                                        return maxChildren;
                                    }

                                    
                                    public void setMaxChildren(String value) {
                                        this.maxChildren = value;
                                    }

                                    
                                    public String getMaxAdults() {
                                        return maxAdults;
                                    }

                                    
                                    public void setMaxAdults(String value) {
                                        this.maxAdults = value;
                                    }

                                    
                                    public String getMaxChildAge() {
                                        return maxChildAge;
                                    }

                                    
                                    public void setMaxChildAge(String value) {
                                        this.maxChildAge = value;
                                    }

                                    
                                    public String getMinChildAge() {
                                        return minChildAge;
                                    }

                                    
                                    public void setMinChildAge(String value) {
                                        this.minChildAge = value;
                                    }

                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "value"
                                })
                                public static class ShippingDetails {

                                    @XmlValue
                                    protected String value;
                                    @XmlAttribute(name = "available")
                                    protected String available;

                                    
                                    public String getValue() {
                                        return value;
                                    }

                                    
                                    public void setValue(String value) {
                                        this.value = value;
                                    }

                                    
                                    public String getAvailable() {
                                        return available;
                                    }

                                    
                                    public void setAvailable(String value) {
                                        this.available = value;
                                    }

                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "value"
                                })
                                public static class SupplierDetails {

                                    @XmlValue
                                    protected String value;
                                    @XmlAttribute(name = "available")
                                    protected String available;

                                    
                                    public String getValue() {
                                        return value;
                                    }

                                    
                                    public void setValue(String value) {
                                        this.value = value;
                                    }

                                    
                                    public String getAvailable() {
                                        return available;
                                    }

                                    
                                    public void setAvailable(String value) {
                                        this.available = value;
                                    }

                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "value"
                                })
                                public static class Vouchers {

                                    @XmlValue
                                    protected String value;
                                    @XmlAttribute(name = "available")
                                    protected String available;

                                    
                                    public String getValue() {
                                        return value;
                                    }

                                    
                                    public void setValue(String value) {
                                        this.value = value;
                                    }

                                    
                                    public String getAvailable() {
                                        return available;
                                    }

                                    
                                    public void setAvailable(String value) {
                                        this.available = value;
                                    }

                                }

                            }

                        }

                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "value"
                    })
                    public static class Confirmation {

                        @XmlValue
                        protected String value;
                        @XmlAttribute(name = "ID")
                        protected Integer id;
                        @XmlAttribute(name = "ID_Context")
                        protected String idContext;
                        @XmlAttribute(name = "Type")
                        protected Integer type;
                        @XmlAttribute(name = "Instance")
                        protected String instance;

                        
                        public String getValue() {
                            return value;
                        }

                        
                        public void setValue(String value) {
                            this.value = value;
                        }

                        
                        public Integer getID() {
                            return id;
                        }

                        
                        public void setID(Integer value) {
                            this.id = value;
                        }

                        
                        public String getIDContext() {
                            return idContext;
                        }

                        
                        public void setIDContext(String value) {
                            this.idContext = value;
                        }

                        
                        public Integer getType() {
                            return type;
                        }

                        
                        public void setType(Integer value) {
                            this.type = value;
                        }

                        
                        public String getInstance() {
                            return instance;
                        }

                        
                        public void setInstance(String value) {
                            this.instance = value;
                        }

                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "value"
                    })
                    public static class Extra {

                        @XmlValue
                        protected String value;
                        @XmlAttribute(name = "available")
                        protected String available;

                        
                        public String getValue() {
                            return value;
                        }

                        
                        public void setValue(String value) {
                            this.value = value;
                        }

                        
                        public String getAvailable() {
                            return available;
                        }

                        
                        public void setAvailable(String value) {
                            this.available = value;
                        }

                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "region"
                    })
                    public static class Location {

                        @XmlElement(name = "Region", required = true)
                        protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Location.Region region;

                        
                        public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Location.Region getRegion() {
                            return region;
                        }

                        
                        public void setRegion(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Location.Region value) {
                            this.region = value;
                        }


                        
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "value"
                        })
                        public static class Region {

                            @XmlValue
                            protected String value;
                            @XmlAttribute(name = "RegionCode")
                            protected Short regionCode;

                            
                            public String getValue() {
                                return value;
                            }

                            
                            public void setValue(String value) {
                                this.value = value;
                            }

                            
                            public Short getRegionCode() {
                                return regionCode;
                            }

                            
                            public void setRegionCode(Short value) {
                                this.regionCode = value;
                            }

                        }

                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "category"
                    })
                    public static class ParticipantInfo {

                        @XmlElement(name = "Category", required = true)
                        protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.ParticipantInfo.Category category;
                        @XmlAttribute(name = "available")
                        protected String available;

                        
                        public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.ParticipantInfo.Category getCategory() {
                            return category;
                        }

                        
                        public void setCategory(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.ParticipantInfo.Category value) {
                            this.category = value;
                        }

                        
                        public String getAvailable() {
                            return available;
                        }

                        
                        public void setAvailable(String value) {
                            this.available = value;
                        }


                        
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "qualifierInfo",
                            "contact"
                        })
                        public static class Category {

                            @XmlElement(name = "QualifierInfo", required = true)
                            protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.ParticipantInfo.Category.QualifierInfo qualifierInfo;
                            @XmlElement(name = "Contact", required = true)
                            protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.ParticipantInfo.Category.Contact contact;
                            @XmlAttribute(name = "Age")
                            protected String age;
                            @XmlAttribute(name = "ParticipantCategoryID")
                            protected String participantCategoryID;

                            
                            public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.ParticipantInfo.Category.QualifierInfo getQualifierInfo() {
                                return qualifierInfo;
                            }

                            
                            public void setQualifierInfo(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.ParticipantInfo.Category.QualifierInfo value) {
                                this.qualifierInfo = value;
                            }

                            
                            public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.ParticipantInfo.Category.Contact getContact() {
                                return contact;
                            }

                            
                            public void setContact(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.ParticipantInfo.Category.Contact value) {
                                this.contact = value;
                            }

                            
                            public String getAge() {
                                return age;
                            }

                            
                            public void setAge(String value) {
                                this.age = value;
                            }

                            
                            public String getParticipantCategoryID() {
                                return participantCategoryID;
                            }

                            
                            public void setParticipantCategoryID(String value) {
                                this.participantCategoryID = value;
                            }


                            
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "personName",
                                "telephone"
                            })
                            public static class Contact {

                                @XmlElement(name = "PersonName", required = true)
                                protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.ParticipantInfo.Category.Contact.PersonName personName;
                                @XmlElement(name = "Telephone", required = true)
                                protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.ParticipantInfo.Category.Contact.Telephone telephone;

                                
                                public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.ParticipantInfo.Category.Contact.PersonName getPersonName() {
                                    return personName;
                                }

                                
                                public void setPersonName(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.ParticipantInfo.Category.Contact.PersonName value) {
                                    this.personName = value;
                                }

                                
                                public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.ParticipantInfo.Category.Contact.Telephone getTelephone() {
                                    return telephone;
                                }

                                
                                public void setTelephone(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.ParticipantInfo.Category.Contact.Telephone value) {
                                    this.telephone = value;
                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "givenName",
                                    "middleName",
                                    "surname"
                                })
                                public static class PersonName {

                                    @XmlElement(name = "GivenName", required = true)
                                    protected String givenName;
                                    @XmlElement(name = "MiddleName", required = true)
                                    protected String middleName;
                                    @XmlElement(name = "Surname", required = true)
                                    protected String surname;

                                    
                                    public String getGivenName() {
                                        return givenName;
                                    }

                                    
                                    public void setGivenName(String value) {
                                        this.givenName = value;
                                    }

                                    
                                    public String getMiddleName() {
                                        return middleName;
                                    }

                                    
                                    public void setMiddleName(String value) {
                                        this.middleName = value;
                                    }

                                    
                                    public String getSurname() {
                                        return surname;
                                    }

                                    
                                    public void setSurname(String value) {
                                        this.surname = value;
                                    }

                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "value"
                                })
                                public static class Telephone {

                                    @XmlValue
                                    protected String value;
                                    @XmlAttribute(name = "PhoneNumber")
                                    protected String phoneNumber;

                                    
                                    public String getValue() {
                                        return value;
                                    }

                                    
                                    public void setValue(String value) {
                                        this.value = value;
                                    }

                                    
                                    public String getPhoneNumber() {
                                        return phoneNumber;
                                    }

                                    
                                    public void setPhoneNumber(String value) {
                                        this.phoneNumber = value;
                                    }

                                }

                            }


                            
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "value"
                            })
                            public static class QualifierInfo {

                                @XmlValue
                                protected String value;
                                @XmlAttribute(name = "Extension")
                                protected String extension;

                                
                                public String getValue() {
                                    return value;
                                }

                                
                                public void setValue(String value) {
                                    this.value = value;
                                }

                                
                                public String getExtension() {
                                    return extension;
                                }

                                
                                public void setExtension(String value) {
                                    this.extension = value;
                                }

                            }

                        }

                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "value"
                    })
                    public static class PickupDropoff {

                        @XmlValue
                        protected String value;
                        @XmlAttribute(name = "available")
                        protected String available;

                        
                        public String getValue() {
                            return value;
                        }

                        
                        public void setValue(String value) {
                            this.value = value;
                        }

                        
                        public String getAvailable() {
                            return available;
                        }

                        
                        public void setAvailable(String value) {
                            this.available = value;
                        }

                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "summary",
                        "participantCategory"
                    })
                    public static class Pricing {

                        @XmlElement(name = "Summary", required = true)
                        protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Pricing.Summary summary;
                        @XmlElement(name = "ParticipantCategory", required = true)
                        protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Pricing.ParticipantCategory participantCategory;
                        @XmlAttribute(name = "available")
                        protected String available;

                        
                        public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Pricing.Summary getSummary() {
                            return summary;
                        }

                        
                        public void setSummary(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Pricing.Summary value) {
                            this.summary = value;
                        }

                        
                        public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Pricing.ParticipantCategory getParticipantCategory() {
                            return participantCategory;
                        }

                        
                        public void setParticipantCategory(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Pricing.ParticipantCategory value) {
                            this.participantCategory = value;
                        }

                        
                        public String getAvailable() {
                            return available;
                        }

                        
                        public void setAvailable(String value) {
                            this.available = value;
                        }


                        
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "qualifierInfo",
                            "price"
                        })
                        public static class ParticipantCategory {

                            @XmlElement(name = "QualifierInfo", required = true)
                            protected String qualifierInfo;
                            @XmlElement(name = "Price", required = true)
                            protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Pricing.ParticipantCategory.Price price;
                            @XmlAttribute(name = "Age")
                            protected String age;

                            
                            public String getQualifierInfo() {
                                return qualifierInfo;
                            }

                            
                            public void setQualifierInfo(String value) {
                                this.qualifierInfo = value;
                            }

                            
                            public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Pricing.ParticipantCategory.Price getPrice() {
                                return price;
                            }

                            
                            public void setPrice(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Pricing.ParticipantCategory.Price value) {
                                this.price = value;
                            }

                            
                            public String getAge() {
                                return age;
                            }

                            
                            public void setAge(String value) {
                                this.age = value;
                            }


                            
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "value"
                            })
                            public static class Price {

                                @XmlValue
                                protected String value;
                                @XmlAttribute(name = "Amount")
                                protected Float amount;
                                @XmlAttribute(name = "CurrencyCode")
                                protected String currencyCode;

                                
                                public String getValue() {
                                    return value;
                                }

                                
                                public void setValue(String value) {
                                    this.value = value;
                                }

                                
                                public Float getAmount() {
                                    return amount;
                                }

                                
                                public void setAmount(Float value) {
                                    this.amount = value;
                                }

                                
                                public String getCurrencyCode() {
                                    return currencyCode;
                                }

                                
                                public void setCurrencyCode(String value) {
                                    this.currencyCode = value;
                                }

                            }

                        }


                        
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "taxAmounts"
                        })
                        public static class Summary {

                            @XmlElement(name = "TaxAmounts", required = true)
                            protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Pricing.Summary.TaxAmounts taxAmounts;
                            @XmlAttribute(name = "Amount")
                            protected Float amount;
                            @XmlAttribute(name = "CurrencyCode")
                            protected String currencyCode;

                            
                            public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Pricing.Summary.TaxAmounts getTaxAmounts() {
                                return taxAmounts;
                            }

                            
                            public void setTaxAmounts(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Pricing.Summary.TaxAmounts value) {
                                this.taxAmounts = value;
                            }

                            
                            public Float getAmount() {
                                return amount;
                            }

                            
                            public void setAmount(Float value) {
                                this.amount = value;
                            }

                            
                            public String getCurrencyCode() {
                                return currencyCode;
                            }

                            
                            public void setCurrencyCode(String value) {
                                this.currencyCode = value;
                            }


                            
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "taxAmount"
                            })
                            public static class TaxAmounts {

                                @XmlElement(name = "TaxAmount", required = true)
                                protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Pricing.Summary.TaxAmounts.TaxAmount taxAmount;
                                @XmlAttribute(name = "available")
                                protected String available;

                                
                                public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Pricing.Summary.TaxAmounts.TaxAmount getTaxAmount() {
                                    return taxAmount;
                                }

                                
                                public void setTaxAmount(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.Pricing.Summary.TaxAmounts.TaxAmount value) {
                                    this.taxAmount = value;
                                }

                                
                                public String getAvailable() {
                                    return available;
                                }

                                
                                public void setAvailable(String value) {
                                    this.available = value;
                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "value"
                                })
                                public static class TaxAmount {

                                    @XmlValue
                                    protected String value;
                                    @XmlAttribute(name = "Total")
                                    protected Integer total;
                                    @XmlAttribute(name = "TaxCode")
                                    protected String taxCode;
                                    @XmlAttribute(name = "Percentage")
                                    protected String percentage;

                                    
                                    public String getValue() {
                                        return value;
                                    }

                                    
                                    public void setValue(String value) {
                                        this.value = value;
                                    }

                                    
                                    public Integer getTotal() {
                                        return total;
                                    }

                                    
                                    public void setTotal(Integer value) {
                                        this.total = value;
                                    }

                                    
                                    public String getTaxCode() {
                                        return taxCode;
                                    }

                                    
                                    public void setTaxCode(String value) {
                                        this.taxCode = value;
                                    }

                                    
                                    public String getPercentage() {
                                        return percentage;
                                    }

                                    
                                    public void setPercentage(String value) {
                                        this.percentage = value;
                                    }

                                }

                            }

                        }

                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "value"
                    })
                    public static class Schedule {

                        @XmlValue
                        protected String value;
                        @XmlAttribute(name = "Start")
                        @XmlSchemaType(name = "dateTime")
                        protected String start;
                        @XmlAttribute(name = "End")
                        protected String end;

                        
                        public String getValue() {
                            return value;
                        }

                        
                        public void setValue(String value) {
                            this.value = value;
                        }

                        
                        public String getStart() {
                            return start;
                        }

                        
                        public void setStart(String value) {
                            this.start = value;
                        }

                        
                        public String getEnd() {
                            return end;
                        }

                        
                        public void setEnd(String value) {
                            this.end = value;
                        }

                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "activityTPA"
                    })
                    public static class TPAExtensions {

                        @XmlElement(name = "Activity_TPA", required = true)
                        protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.TPAExtensions.ActivityTPA activityTPA;

                        
                        public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.TPAExtensions.ActivityTPA getActivityTPA() {
                            return activityTPA;
                        }

                        
                        public void setActivityTPA(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.TPAExtensions.ActivityTPA value) {
                            this.activityTPA = value;
                        }


                        
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "contactDetail"
                        })
                        public static class ActivityTPA {

                            @XmlElement(name = "ContactDetail", required = true)
                            protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.TPAExtensions.ActivityTPA.ContactDetail contactDetail;

                            
                            public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.TPAExtensions.ActivityTPA.ContactDetail getContactDetail() {
                                return contactDetail;
                            }

                            
                            public void setContactDetail(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.TPAExtensions.ActivityTPA.ContactDetail value) {
                                this.contactDetail = value;
                            }


                            
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "personName",
                                "telephone"
                            })
                            public static class ContactDetail {

                                @XmlElement(name = "PersonName", required = true)
                                protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.TPAExtensions.ActivityTPA.ContactDetail.PersonName personName;
                                @XmlElement(name = "Telephone", required = true)
                                protected BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.TPAExtensions.ActivityTPA.ContactDetail.Telephone telephone;
                                @XmlAttribute(name = "available")
                                protected String available;

                                
                                public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.TPAExtensions.ActivityTPA.ContactDetail.PersonName getPersonName() {
                                    return personName;
                                }

                                
                                public void setPersonName(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.TPAExtensions.ActivityTPA.ContactDetail.PersonName value) {
                                    this.personName = value;
                                }

                                
                                public BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.TPAExtensions.ActivityTPA.ContactDetail.Telephone getTelephone() {
                                    return telephone;
                                }

                                
                                public void setTelephone(BookRS.ResponseBody.OTATourActivityBookRSWrapper.OTATourActivityBookRS.ReservationDetails.TPAExtensions.ActivityTPA.ContactDetail.Telephone value) {
                                    this.telephone = value;
                                }

                                
                                public String getAvailable() {
                                    return available;
                                }

                                
                                public void setAvailable(String value) {
                                    this.available = value;
                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "namePrefix",
                                    "givenName",
                                    "surname"
                                })
                                public static class PersonName {

                                    @XmlElement(name = "NamePrefix", required = true)
                                    protected String namePrefix;
                                    @XmlElement(name = "GivenName", required = true)
                                    protected String givenName;
                                    @XmlElement(name = "Surname", required = true)
                                    protected String surname;

                                    
                                    public String getNamePrefix() {
                                        return namePrefix;
                                    }

                                    
                                    public void setNamePrefix(String value) {
                                        this.namePrefix = value;
                                    }

                                    
                                    public String getGivenName() {
                                        return givenName;
                                    }

                                    
                                    public void setGivenName(String value) {
                                        this.givenName = value;
                                    }

                                    
                                    public String getSurname() {
                                        return surname;
                                    }

                                    
                                    public void setSurname(String value) {
                                        this.surname = value;
                                    }

                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "value"
                                })
                                public static class Telephone {

                                    @XmlValue
                                    protected String value;
                                    @XmlAttribute(name = "PhoneNumber")
                                    protected Long phoneNumber;

                                    
                                    public String getValue() {
                                        return value;
                                    }

                                    
                                    public void setValue(String value) {
                                        this.value = value;
                                    }

                                    
                                    public Long getPhoneNumber() {
                                        return phoneNumber;
                                    }

                                    
                                    public void setPhoneNumber(Long value) {
                                        this.phoneNumber = value;
                                    }

                                }

                            }

                        }

                    }

                }

            }

        }

    }


    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "status",
        "userID",
        "sessionID",
        "transactionID"
    })
    public static class ResponseHeader {

        @XmlElement(name = "Status", required = true)
        protected String status;
        @XmlElement(name = "UserID", required = true)
        protected String userID;
        @XmlElement(name = "SessionID", required = true)
        protected String sessionID;
        @XmlElement(name = "TransactionID", required = true)
        protected String transactionID;

        
        public String getStatus() {
            return status;
        }

        
        public void setStatus(String value) {
            this.status = value;
        }

        
        public String getUserID() {
            return userID;
        }

        
        public void setUserID(String value) {
            this.userID = value;
        }

        
        public String getSessionID() {
            return sessionID;
        }

        
        public void setSessionID(String value) {
            this.sessionID = value;
        }

        
        public String getTransactionID() {
            return transactionID;
        }

        
        public void setTransactionID(String value) {
            this.transactionID = value;
        }

    }

}
