//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.12 at 04:34:46 PM IST 
//


package com.cnk.siapi.response;

import javax.xml.bind.annotation.XmlRegistry;



@XmlRegistry
public class CommonGetPolicyObjectFactory {


    
    public CommonGetPolicyObjectFactory() {
    }

    
    public CommonGetPolicyRS createCommonGetPolicyRS() {
        return new CommonGetPolicyRS();
    }

    
    public CommonGetPolicyRS.ResponseBody createCommonGetPolicyRSResponseBody() {
        return new CommonGetPolicyRS.ResponseBody();
    }

    
    public CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper createCommonGetPolicyRSResponseBodyOTATourActivityCancellationPoliciesRSWrapper() {
        return new CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper();
    }
    
    
    public CommonGetPolicyRS.ResponseBody.ErrorList createCommonGetPolicyRSResponseBodyErrorList() {
        return new CommonGetPolicyRS.ResponseBody.ErrorList();
    }

    
    public CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.OTATourActivityCancellationPoliciesRS createCommonGetPolicyRSResponseBodyOTATourActivityCancellationPoliciesRSWrapperOTATourActivityCancellationPoliciesRS() {
        return new CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.OTATourActivityCancellationPoliciesRS();
    }
    
    
    public CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.ErrorList createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperErrorList() {
        return new CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.ErrorList();
    }
    
    
    public CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.ErrorList.Error createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperErrorListError() {
        return new CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.ErrorList.Error();
    }
    
    
    public CommonGetPolicyRS.ResponseHeader createCommonGetPolicyRSResponseHeader() {
        return new CommonGetPolicyRS.ResponseHeader();
    }

    
    public CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.OTATourActivityCancellationPoliciesRS.CancellationPolicies createCommonGetPolicyRSResponseBodyOTATourActivityCancellationPoliciesRSWrapperOTATourActivityCancellationPoliciesRSCancellationPolicies() {
        return new CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.OTATourActivityCancellationPoliciesRS.CancellationPolicies();
    }

}
