//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.12 at 04:34:05 PM IST 
//


package com.cnk.siapi.response;

import javax.xml.bind.annotation.XmlRegistry;



@XmlRegistry
public class CommonCancelObjectFactory {


    
    public CommonCancelObjectFactory() {
    }

    
    public CommonCancelRS createCommonCancelRS() {
        return new CommonCancelRS();
    }

    
    public CommonCancelRS.ResponseBody createCommonCancelRSResponseBody() {
        return new CommonCancelRS.ResponseBody();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapper() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper();
    }
    
    public CommonCancelRS.ResponseBody.ErrorList createCommonCancelRSResponseBodyErrorList() {
        return new CommonCancelRS.ResponseBody.ErrorList();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRS() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS();
    }
    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.ErrorList createCommonCancelRSResponseBodyOTATourActivityAvailRSWrapperErrorList() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.ErrorList();
    }
    
    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.ErrorList.Error createCommonCancelRSResponseBodyOTATourActivityAvailRSWrapperErrorListError() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.ErrorList.Error();
    }
    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Errors createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSErrors() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Errors();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservation() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfo() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.TPAExtensions createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoTPAExtensions() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.TPAExtensions();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.TPAExtensions.ActivityTPA createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoTPAExtensionsActivityTPA() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.TPAExtensions.ActivityTPA();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.TPAExtensions.ActivityTPA.ContactDetail createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoTPAExtensionsActivityTPAContactDetail() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.TPAExtensions.ActivityTPA.ContactDetail();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.SupplierOperator createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoSupplierOperator() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.SupplierOperator();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.SupplierOperator.Contact createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoSupplierOperatorContact() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.SupplierOperator.Contact();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Pricing createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoPricing() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Pricing();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Pricing.ParticipantCategory createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoPricingParticipantCategory() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Pricing.ParticipantCategory();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Pricing.ParticipantCategory.TPAExtensions createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoPricingParticipantCategoryTPAExtensions() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Pricing.ParticipantCategory.TPAExtensions();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Pricing.ParticipantCategory.Price createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoPricingParticipantCategoryPrice() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Pricing.ParticipantCategory.Price();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Pricing.ParticipantCategory.Price.TaxAmounts createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoPricingParticipantCategoryPriceTaxAmounts() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Pricing.ParticipantCategory.Price.TaxAmounts();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Pricing.Summary createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoPricingSummary() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Pricing.Summary();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Pricing.Summary.TaxAmounts createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoPricingSummaryTaxAmounts() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Pricing.Summary.TaxAmounts();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Location createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoLocation() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Location();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.ParticipantInfo createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoParticipantInfo() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.ParticipantInfo();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.ParticipantInfo.Category createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoParticipantInfoCategory() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.ParticipantInfo.Category();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.ParticipantInfo.Category.Contact createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoParticipantInfoCategoryContact() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.ParticipantInfo.Category.Contact();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoBasicInfo() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo.TPAExtensions createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoBasicInfoTPAExtensions() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo.TPAExtensions();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo.TPAExtensions.ActivityTPA createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoBasicInfoTPAExtensionsActivityTPA() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo.TPAExtensions.ActivityTPA();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo.TPAExtensions.ActivityTPA.Answers createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoBasicInfoTPAExtensionsActivityTPAAnswers() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo.TPAExtensions.ActivityTPA.Answers();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo.TPAExtensions.ActivityTPA.Answers.Answer createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoBasicInfoTPAExtensionsActivityTPAAnswersAnswer() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo.TPAExtensions.ActivityTPA.Answers.Answer();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo.TPAExtensions.ActivityTPA.Participant createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoBasicInfoTPAExtensionsActivityTPAParticipant() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo.TPAExtensions.ActivityTPA.Participant();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.CancelConfirmation createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationCancelConfirmation() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.CancelConfirmation();
    }

    
    public CommonCancelRS.ResponseHeader createCommonCancelRSResponseHeader() {
        return new CommonCancelRS.ResponseHeader();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Errors.Error createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSErrorsError() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Errors.Error();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReferenceID createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReferenceID() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReferenceID();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Description createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoDescription() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Description();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.TPAExtensions.ActivityTPA.Price createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoTPAExtensionsActivityTPAPrice() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.TPAExtensions.ActivityTPA.Price();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.TPAExtensions.ActivityTPA.ContactDetail.PersonName createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoTPAExtensionsActivityTPAContactDetailPersonName() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.TPAExtensions.ActivityTPA.ContactDetail.PersonName();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.TPAExtensions.ActivityTPA.ContactDetail.Telephone createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoTPAExtensionsActivityTPAContactDetailTelephone() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.TPAExtensions.ActivityTPA.ContactDetail.Telephone();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.TPAExtensions.ActivityTPA.ContactDetail.Address createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoTPAExtensionsActivityTPAContactDetailAddress() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.TPAExtensions.ActivityTPA.ContactDetail.Address();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.SupplierOperator.Name createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoSupplierOperatorName() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.SupplierOperator.Name();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.SupplierOperator.Contact.Telephone createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoSupplierOperatorContactTelephone() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.SupplierOperator.Contact.Telephone();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Pricing.ParticipantCategory.TPAExtensions.ActivityTPA createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoPricingParticipantCategoryTPAExtensionsActivityTPA() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Pricing.ParticipantCategory.TPAExtensions.ActivityTPA();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Pricing.ParticipantCategory.Price.TaxAmounts.TaxAmount createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoPricingParticipantCategoryPriceTaxAmountsTaxAmount() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Pricing.ParticipantCategory.Price.TaxAmounts.TaxAmount();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Pricing.Summary.TaxAmounts.TaxAmount createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoPricingSummaryTaxAmountsTaxAmount() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Pricing.Summary.TaxAmounts.TaxAmount();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Location.Address createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoLocationAddress() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Location.Address();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Location.Region createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoLocationRegion() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.Location.Region();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.ParticipantInfo.Category.QualifierInfo createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoParticipantInfoCategoryQualifierInfo() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.ParticipantInfo.Category.QualifierInfo();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.ParticipantInfo.Category.TPAExtensions createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoParticipantInfoCategoryTPAExtensions() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.ParticipantInfo.Category.TPAExtensions();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.ParticipantInfo.Category.Contact.PersonName createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoParticipantInfoCategoryContactPersonName() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.ParticipantInfo.Category.Contact.PersonName();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.ParticipantInfo.Category.Contact.Telephone createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoParticipantInfoCategoryContactTelephone() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.ParticipantInfo.Category.Contact.Telephone();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo.TPAExtensions.ActivityTPA.CancellationPolicy createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoBasicInfoTPAExtensionsActivityTPACancellationPolicy() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo.TPAExtensions.ActivityTPA.CancellationPolicy();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo.TPAExtensions.ActivityTPA.SupplierDetails createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoBasicInfoTPAExtensionsActivityTPASupplierDetails() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo.TPAExtensions.ActivityTPA.SupplierDetails();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo.TPAExtensions.ActivityTPA.Vouchers createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoBasicInfoTPAExtensionsActivityTPAVouchers() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo.TPAExtensions.ActivityTPA.Vouchers();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo.TPAExtensions.ActivityTPA.InvoiceCompany createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoBasicInfoTPAExtensionsActivityTPAInvoiceCompany() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo.TPAExtensions.ActivityTPA.InvoiceCompany();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo.TPAExtensions.ActivityTPA.Answers.Answer.Question createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoBasicInfoTPAExtensionsActivityTPAAnswersAnswerQuestion() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo.TPAExtensions.ActivityTPA.Answers.Answer.Question();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo.TPAExtensions.ActivityTPA.Participant.QualifierInfo createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationReservationInfoBasicInfoTPAExtensionsActivityTPAParticipantQualifierInfo() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.ReservationInfo.BasicInfo.TPAExtensions.ActivityTPA.Participant.QualifierInfo();
    }

    
    public CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.CancelConfirmation.UniqueID createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSReservationCancelConfirmationUniqueID() {
        return new CommonCancelRS.ResponseBody.OTATourActivityCancelRSWrapper.OTATourActivityCancelRS.Reservation.CancelConfirmation.UniqueID();
    }

}
