//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.12 at 04:35:32 PM IST 
//


package com.cnk.siapi.response;

import javax.xml.bind.annotation.XmlRegistry;



@XmlRegistry
public class CommonRetrieveObjectFactory {


    
    public CommonRetrieveObjectFactory() {
    }

    
    public CommonRetrieveRS createCommonRetrieveRS() {
        return new CommonRetrieveRS();
    }

    
    public CommonRetrieveRS.ResponseBody createCommonRetrieveRSResponseBody() {
        return new CommonRetrieveRS.ResponseBody();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapper() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper();
    }
    
    
    public CommonRetrieveRS.ResponseBody.ErrorList createCommonRetrieveRSResponseBodyErrorList() {
        return new CommonRetrieveRS.ResponseBody.ErrorList();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRS() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.ErrorList createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperErrorList() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.ErrorList();
    }
    
    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.ErrorList.Error createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperErrorListError() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.ErrorList.Error();
    }
    
    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetail() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailTPAExtensions() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions.ActivityTPA createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailTPAExtensionsActivityTPA() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions.ActivityTPA();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions.ActivityTPA.ContactDetail createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailTPAExtensionsActivityTPAContactDetail() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions.ActivityTPA.ContactDetail();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailPricing() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.ParticipantCategory createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailPricingParticipantCategory() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.ParticipantCategory();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.Summary createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailPricingSummary() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.Summary();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.Summary.TaxAmounts createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailPricingSummaryTaxAmounts() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.Summary.TaxAmounts();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Extras createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailExtras() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Extras();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Location createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailLocation() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Location();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailParticipantInfo() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailParticipantInfoCategory() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category.Contact createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailParticipantInfoCategoryContact() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category.Contact();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailBasicInfo() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailBasicInfoTPAExtensions() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailBasicInfoTPAExtensionsActivityTPA() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA();
    }

    
    public CommonRetrieveRS.ResponseHeader createCommonRetrieveRSResponseHeader() {
        return new CommonRetrieveRS.ResponseHeader();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Confirmation createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailConfirmation() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Confirmation();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Schedule createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailSchedule() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Schedule();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.PickupDropoff createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailPickupDropoff() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.PickupDropoff();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions.ActivityTPA.ContactDetail.PersonName createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailTPAExtensionsActivityTPAContactDetailPersonName() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions.ActivityTPA.ContactDetail.PersonName();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions.ActivityTPA.ContactDetail.Telephone createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailTPAExtensionsActivityTPAContactDetailTelephone() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions.ActivityTPA.ContactDetail.Telephone();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.ParticipantCategory.Price createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailPricingParticipantCategoryPrice() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.ParticipantCategory.Price();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.Summary.TaxAmounts.TaxAmount createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailPricingSummaryTaxAmountsTaxAmount() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.Summary.TaxAmounts.TaxAmount();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Extras.Extra createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailExtrasExtra() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Extras.Extra();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Location.Region createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailLocationRegion() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Location.Region();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category.QualifierInfo createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailParticipantInfoCategoryQualifierInfo() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category.QualifierInfo();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category.Contact.PersonName createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailParticipantInfoCategoryContactPersonName() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category.Contact.PersonName();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category.Contact.Telephone createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailParticipantInfoCategoryContactTelephone() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category.Contact.Telephone();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA.Participant createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailBasicInfoTPAExtensionsActivityTPAParticipant() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA.Participant();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA.SupplierDetails createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailBasicInfoTPAExtensionsActivityTPASupplierDetails() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA.SupplierDetails();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA.Vouchers createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailBasicInfoTPAExtensionsActivityTPAVouchers() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA.Vouchers();
    }

    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA.Answers createCommonRetrieveRSResponseBodyOTATourActivityResRetrieveRSIntWrapperOTATourActivityResRetrieveRSDetailBasicInfoTPAExtensionsActivityTPAAnswers() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA.Answers();
    }
    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Errors createCommonRetrieveRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSErrors() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Errors();
    }
    
    
    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Errors.Error createCommonRetrieveRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSErrorsError() {
        return new CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Errors.Error();
    }

}
