//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.12 at 04:35:32 PM IST 
//


package com.cnk.siapi.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responseHeader",
    "responseBody"
})
@XmlRootElement(name = "SightSeeingInterfaceRS")
public class CommonRetrieveRS {

    @XmlElement(name = "ResponseHeader", required = true)
    protected CommonRetrieveRS.ResponseHeader responseHeader;
    @XmlElement(name = "ResponseBody", required = true)
    protected CommonRetrieveRS.ResponseBody responseBody;

    
    public CommonRetrieveRS.ResponseHeader getResponseHeader() {
        return responseHeader;
    }

    
    public void setResponseHeader(CommonRetrieveRS.ResponseHeader value) {
        this.responseHeader = value;
    }

    
    public CommonRetrieveRS.ResponseBody getResponseBody() {
        return responseBody;
    }

    
    public void setResponseBody(CommonRetrieveRS.ResponseBody value) {
        this.responseBody = value;
    }


    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
    	"cnkStatus",
        "otaTourActivityResRetrieveRSIntWrapper",
        "errorList"
    })
    public static class ResponseBody {

    	@XmlElement(name = "CNKStatus", required = true)
        protected String cnkStatus;
        @XmlElement(name = "OTA_TourActivityResRetrieveRSIntWrapper", required = true)
        protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper otaTourActivityResRetrieveRSIntWrapper;
        @XmlElement(name = "ErrorList", required = true)
        protected CommonRetrieveRS.ResponseBody.ErrorList errorList;
        
        
        public String getCnkStatus() {
			return cnkStatus;
		}


		public void setCnkStatus(String cnkStatus) {
			this.cnkStatus = cnkStatus;
		}

        
        public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper getOTATourActivityResRetrieveRSIntWrapper() {
            return otaTourActivityResRetrieveRSIntWrapper;
        }

        
        public void setOTATourActivityResRetrieveRSIntWrapper(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper value) {
            this.otaTourActivityResRetrieveRSIntWrapper = value;
        }

        
        public CommonRetrieveRS.ResponseBody.ErrorList getErrorList() {
			return errorList;
		}


		public void setErrorList(CommonRetrieveRS.ResponseBody.ErrorList errorList) {
			this.errorList = errorList;
		}


		@XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "supplierID",
            "accessCode",
            "otaTourActivityResRetrieveRS",
            "errorList"
        })
        public static class OTATourActivityResRetrieveRSIntWrapper {

            @XmlElement(name = "SupplierID", required = true)
            protected String supplierID;
            @XmlElement(name = "Sequence")
            protected String accessCode;
            @XmlElement(name = "OTA_TourActivityResRetrieveRS", required = true)
            protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS otaTourActivityResRetrieveRS;
            @XmlElement(name = "ErrorList", required = true)
            protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.ErrorList errorList;
            
            public String getSupplierID() {
                return supplierID;
            }

            
            public void setSupplierID(String value) {
                this.supplierID = value;
            }

            
            public String getAccessCode() {
                return accessCode;
            }

            
            public void setAccessCode(String value) {
                this.accessCode = value;
            }

            
            public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS getOTATourActivityResRetrieveRS() {
                return otaTourActivityResRetrieveRS;
            }

            
            public void setOTATourActivityResRetrieveRS(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS value) {
                this.otaTourActivityResRetrieveRS = value;
            }

            
            public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.ErrorList getErrorList() {
				return errorList;
			}

            
			public void setErrorList(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.ErrorList errorList) {
				this.errorList = errorList;
			}
            
            
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "success",
                "detail",
                "errors"
            })
            public static class OTATourActivityResRetrieveRS {

                @XmlElement(name = "Success", required = true)
                protected String success;
                @XmlElement(name = "Detail", required = true)
                protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail detail;
                @XmlElement(name = "Errors", required = true)
                protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Errors errors;
                
                public String getSuccess() {
                    return success;
                }

                
                public void setSuccess(String value) {
                    this.success = value;
                }

                
                public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail getDetail() {
                    return detail;
                }

                
                public void setDetail(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail value) {
                    this.detail = value;
                }
                
                
                public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Errors getErrors() {
                    return errors;
                }

                
                public void setErrors(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Errors value) {
                    this.errors = value;
                }
                
                
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "error"
                })
                public static class Errors {

                    @XmlElement(name = "Error", required = true)
                    protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Errors.Error error;

                    
                    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Errors.Error getError() {
                        return error;
                    }

                    
                    public void setError(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Errors.Error value) {
                        this.error = value;
                    }

                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "value"
                    })
                    public static class Error {

                        @XmlValue
                        protected String value;
                        @XmlAttribute(name = "Language")
                        protected String language;
                        @XmlAttribute(name = "Type")
                        protected String type;
                        @XmlAttribute(name = "ShortText")
                        protected String shortText;
                        @XmlAttribute(name = "Code")
                        protected String code;
                        @XmlAttribute(name = "DocURL")
                        protected String docURL;
                        @XmlAttribute(name = "Status")
                        protected String status;
                        @XmlAttribute(name = "Tag")
                        protected String tag;
                        @XmlAttribute(name = "RecordID")
                        protected String recordID;
                        @XmlAttribute(name = "NodeList")
                        protected String nodeList;

                        
                        public String getValue() {
                            return value;
                        }

                        
                        public void setValue(String value) {
                            this.value = value;
                        }

                        
                        public String getLanguage() {
                            return language;
                        }

                        
                        public void setLanguage(String value) {
                            this.language = value;
                        }

                        
                        public String getType() {
                            return type;
                        }

                        
                        public void setType(String value) {
                            this.type = value;
                        }

                        
                        public String getShortText() {
                            return shortText;
                        }

                        
                        public void setShortText(String value) {
                            this.shortText = value;
                        }

                        
                        public String getCode() {
                            return code;
                        }

                        
                        public void setCode(String value) {
                            this.code = value;
                        }

                        
                        public String getDocURL() {
                            return docURL;
                        }

                        
                        public void setDocURL(String value) {
                            this.docURL = value;
                        }

                        
                        public String getStatus() {
                            return status;
                        }

                        
                        public void setStatus(String value) {
                            this.status = value;
                        }

                        
                        public String getTag() {
                            return tag;
                        }

                        
                        public void setTag(String value) {
                            this.tag = value;
                        }

                        
                        public String getRecordID() {
                            return recordID;
                        }

                        
                        public void setRecordID(String value) {
                            this.recordID = value;
                        }

                        
                        public String getNodeList() {
                            return nodeList;
                        }

                        
                        public void setNodeList(String value) {
                            this.nodeList = value;
                        }

                    }

                }
                
                
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "basicInfo",
                    "confirmation",
                    "participantInfo",
                    "schedule",
                    "location",
                    "extras",
                    "pickupDropoff",
                    "pricing",
                    "tpaExtensions"
                })
                public static class Detail {

                    @XmlElement(name = "BasicInfo", required = true)
                    protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo basicInfo;
                    @XmlElement(name = "Confirmation")
                    protected List<CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Confirmation> confirmation;
                    @XmlElement(name = "ParticipantInfo")
                    protected List<CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo> participantInfo;
                    @XmlElement(name = "Schedule", required = true)
                    protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Schedule schedule;
                    @XmlElement(name = "Location", required = true)
                    protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Location location;
                    @XmlElement(name = "Extras", required = true)
                    protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Extras extras;
                    @XmlElement(name = "PickupDropoff", required = true)
                    protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.PickupDropoff pickupDropoff;
                    @XmlElement(name = "Pricing", required = true)
                    protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing pricing;
                    @XmlElement(name = "TPA_Extensions", required = true)
                    protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions tpaExtensions;

                    
                    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo getBasicInfo() {
                        return basicInfo;
                    }

                    
                    public void setBasicInfo(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo value) {
                        this.basicInfo = value;
                    }

                    
                    public List<CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Confirmation> getConfirmation() {
                        if (confirmation == null) {
                            confirmation = new ArrayList<CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Confirmation>();
                        }
                        return this.confirmation;
                    }

                    
                    public List<CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo> getParticipantInfo() {
                        if (participantInfo == null) {
                            participantInfo = new ArrayList<CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo>();
                        }
                        return this.participantInfo;
                    }

                    
                    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Schedule getSchedule() {
                        return schedule;
                    }

                    
                    public void setSchedule(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Schedule value) {
                        this.schedule = value;
                    }

                    
                    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Location getLocation() {
                        return location;
                    }

                    
                    public void setLocation(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Location value) {
                        this.location = value;
                    }

                    
                    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Extras getExtras() {
                        return extras;
                    }

                    
                    public void setExtras(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Extras value) {
                        this.extras = value;
                    }

                    
                    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.PickupDropoff getPickupDropoff() {
                        return pickupDropoff;
                    }

                    
                    public void setPickupDropoff(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.PickupDropoff value) {
                        this.pickupDropoff = value;
                    }

                    
                    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing getPricing() {
                        return pricing;
                    }

                    
                    public void setPricing(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing value) {
                        this.pricing = value;
                    }

                    
                    public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions getTPAExtensions() {
                        return tpaExtensions;
                    }

                    
                    public void setTPAExtensions(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions value) {
                        this.tpaExtensions = value;
                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "tpaExtensions"
                    })
                    public static class BasicInfo {

                        @XmlElement(name = "TPA_Extensions", required = true)
                        protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions tpaExtensions;
                        @XmlAttribute(name = "SupplierProductCode")
                        protected String supplierProductCode;
                        @XmlAttribute(name = "Name")
                        protected String name;

                        
                        public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions getTPAExtensions() {
                            return tpaExtensions;
                        }

                        
                        public void setTPAExtensions(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions value) {
                            this.tpaExtensions = value;
                        }

                        
                        public String getSupplierProductCode() {
                            return supplierProductCode;
                        }

                        
                        public void setSupplierProductCode(String value) {
                            this.supplierProductCode = value;
                        }

                        
                        public String getName() {
                            return name;
                        }

                        
                        public void setName(String value) {
                            this.name = value;
                        }


                        
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "activityTPA"
                        })
                        public static class TPAExtensions {

                            @XmlElement(name = "Activity_TPA", required = true)
                            protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA activityTPA;

                            
                            public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA getActivityTPA() {
                                return activityTPA;
                            }

                            
                            public void setActivityTPA(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA value) {
                                this.activityTPA = value;
                            }


                            
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "participant",
                                "supplierDetails",
                                "vouchers",
                                "answers"
                            })
                            public static class ActivityTPA {

                                @XmlElement(name = "Participant", required = true)
                                protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA.Participant participant;
                                @XmlElement(name = "Supplier_Details", required = true)
                                protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA.SupplierDetails supplierDetails;
                                @XmlElement(name = "Vouchers", required = true)
                                protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA.Vouchers vouchers;
                                @XmlElement(name = "Answers", required = true)
                                protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA.Answers answers;

                                
                                public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA.Participant getParticipant() {
                                    return participant;
                                }

                                
                                public void setParticipant(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA.Participant value) {
                                    this.participant = value;
                                }

                                
                                public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA.SupplierDetails getSupplierDetails() {
                                    return supplierDetails;
                                }

                                
                                public void setSupplierDetails(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA.SupplierDetails value) {
                                    this.supplierDetails = value;
                                }

                                
                                public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA.Vouchers getVouchers() {
                                    return vouchers;
                                }

                                
                                public void setVouchers(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA.Vouchers value) {
                                    this.vouchers = value;
                                }

                                
                                public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA.Answers getAnswers() {
                                    return answers;
                                }

                                
                                public void setAnswers(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.BasicInfo.TPAExtensions.ActivityTPA.Answers value) {
                                    this.answers = value;
                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "value"
                                })
                                public static class Answers {

                                    @XmlValue
                                    protected String value;
                                    @XmlAttribute(name = "available")
                                    protected String available;

                                    
                                    public String getValue() {
                                        return value;
                                    }

                                    
                                    public void setValue(String value) {
                                        this.value = value;
                                    }

                                    
                                    public String getAvailable() {
                                        return available;
                                    }

                                    
                                    public void setAvailable(String value) {
                                        this.available = value;
                                    }

                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "value"
                                })
                                public static class Participant {

                                    @XmlValue
                                    protected String value;
                                    @XmlAttribute(name = "available")
                                    protected String available;
                                    @XmlAttribute(name = "minAdultAge")
                                    protected String minAdultAge;
                                    @XmlAttribute(name = "maxIndividuals")
                                    protected String maxIndividuals;
                                    @XmlAttribute(name = "maxChildren")
                                    protected String maxChildren;
                                    @XmlAttribute(name = "maxAdults")
                                    protected String maxAdults;
                                    @XmlAttribute(name = "maxChildAge")
                                    protected String maxChildAge;
                                    @XmlAttribute(name = "minChildAge")
                                    protected String minChildAge;
                                    @XmlAttribute(name = "maxAdultAge")
                                    protected String maxAdultAge;

                                    
                                    public String getValue() {
                                        return value;
                                    }

                                    
                                    public void setValue(String value) {
                                        this.value = value;
                                    }

                                    
                                    public String getAvailable() {
                                        return available;
                                    }

                                    
                                    public void setAvailable(String value) {
                                        this.available = value;
                                    }

                                    
                                    public String getMinAdultAge() {
                                        return minAdultAge;
                                    }

                                    
                                    public void setMinAdultAge(String value) {
                                        this.minAdultAge = value;
                                    }

                                    
                                    public String getMaxIndividuals() {
                                        return maxIndividuals;
                                    }

                                    
                                    public void setMaxIndividuals(String value) {
                                        this.maxIndividuals = value;
                                    }

                                    
                                    public String getMaxChildren() {
                                        return maxChildren;
                                    }

                                    
                                    public void setMaxChildren(String value) {
                                        this.maxChildren = value;
                                    }

                                    
                                    public String getMaxAdults() {
                                        return maxAdults;
                                    }

                                    
                                    public void setMaxAdults(String value) {
                                        this.maxAdults = value;
                                    }

                                    
                                    public String getMaxChildAge() {
                                        return maxChildAge;
                                    }

                                    
                                    public void setMaxChildAge(String value) {
                                        this.maxChildAge = value;
                                    }

                                    
                                    public String getMinChildAge() {
                                        return minChildAge;
                                    }

                                    
                                    public void setMinChildAge(String value) {
                                        this.minChildAge = value;
                                    }

                                    
                                    public String getMaxAdultAge() {
                                        return maxAdultAge;
                                    }

                                    
                                    public void setMaxAdultAge(String value) {
                                        this.maxAdultAge = value;
                                    }

                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "name",
                                    "id",
                                    "reference",
                                    "rateKey"
                                })
                                public static class SupplierDetails {

                                    @XmlElement(required = true)
                                    protected String name;
                                    @XmlElement(name = "ID", required = true)
                                    protected String id;
                                    @XmlElement(name = "Reference", required = true)
                                    protected String reference;
                                    @XmlElement(name = "RateKey", required = true)
                                    protected String rateKey;
                                    @XmlAttribute(name = "available")
                                    protected String available;

                                    
                                    public String getName() {
                                        return name;
                                    }

                                    
                                    public void setName(String value) {
                                        this.name = value;
                                    }

                                    
                                    public String getID() {
                                        return id;
                                    }

                                    
                                    public void setID(String value) {
                                        this.id = value;
                                    }

                                    
                                    public String getReference() {
                                        return reference;
                                    }

                                    
                                    public void setReference(String value) {
                                        this.reference = value;
                                    }

                                    
                                    public String getRateKey() {
                                        return rateKey;
                                    }

                                    
                                    public void setRateKey(String value) {
                                        this.rateKey = value;
                                    }

                                    
                                    public String getAvailable() {
                                        return available;
                                    }

                                    
                                    public void setAvailable(String value) {
                                        this.available = value;
                                    }

                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "code",
                                    "info"
                                })
                                public static class Vouchers {

                                    @XmlElement(required = true)
                                    protected String code;
                                    @XmlElement(name = "Info", required = true)
                                    protected String info;
                                    @XmlAttribute(name = "available")
                                    protected String available;

                                    
                                    public String getCode() {
                                        return code;
                                    }

                                    
                                    public void setCode(String value) {
                                        this.code = value;
                                    }

                                    
                                    public String getInfo() {
                                        return info;
                                    }

                                    
                                    public void setInfo(String value) {
                                        this.info = value;
                                    }

                                    
                                    public String getAvailable() {
                                        return available;
                                    }

                                    
                                    public void setAvailable(String value) {
                                        this.available = value;
                                    }

                                }

                            }

                        }

                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "value"
                    })
                    public static class Confirmation {

                        @XmlValue
                        protected String value;
                        @XmlAttribute(name = "ID")
                        protected String id;
                        @XmlAttribute(name = "Instance")
                        protected String instance;
                        @XmlAttribute(name = "ID_Context")
                        protected String idContext;
                        @XmlAttribute(name = "Type")
                        protected int type;

                        
                        public String getValue() {
                            return value;
                        }

                        
                        public void setValue(String value) {
                            this.value = value;
                        }

                        
                        public String getID() {
                            return id;
                        }

                        
                        public void setID(String value) {
                            this.id = value;
                        }

                        
                        public String getInstance() {
                            return instance;
                        }

                        
                        public void setInstance(String value) {
                            this.instance = value;
                        }

                        
                        public String getIDContext() {
                            return idContext;
                        }

                        
                        public void setIDContext(String value) {
                            this.idContext = value;
                        }

                        
                        public int getType() {
                            return type;
                        }

                        
                        public void setType(int value) {
                            this.type = value;
                        }

                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "extra"
                    })
                    public static class Extras {

                        @XmlElement(name = "Extra", required = true)
                        protected List<CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Extras.Extra> extra;
                        @XmlAttribute(name = "available")
                        protected String available;

                        
                        public List<CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Extras.Extra> getExtra() {
                            if (extra == null) {
                                extra = new ArrayList<CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Extras.Extra>();
                            }
                            return this.extra;
                        }

                        
                        public String getAvailable() {
                            return available;
                        }

                        
                        public void setAvailable(String value) {
                            this.available = value;
                        }


                        
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "value"
                        })
                        public static class Extra {

                            @XmlValue
                            protected String value;
                            @XmlAttribute(name = "Name")
                            protected String name;
                            @XmlAttribute(name = "Description")
                            protected String description;

                            
                            public String getValue() {
                                return value;
                            }

                            
                            public void setValue(String value) {
                                this.value = value;
                            }

                            
                            public String getName() {
                                return name;
                            }

                            
                            public void setName(String value) {
                                this.name = value;
                            }

                            
                            public String getDescription() {
                                return description;
                            }

                            
                            public void setDescription(String value) {
                                this.description = value;
                            }

                        }

                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "region"
                    })
                    public static class Location {

                        @XmlElement(name = "Region", required = true)
                        protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Location.Region region;
                        @XmlAttribute(name = "available")
                        protected String available;

                        
                        public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Location.Region getRegion() {
                            return region;
                        }

                        
                        public void setRegion(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Location.Region value) {
                            this.region = value;
                        }

                        
                        public String getAvailable() {
                            return available;
                        }

                        
                        public void setAvailable(String value) {
                            this.available = value;
                        }


                        
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "value"
                        })
                        public static class Region {

                            @XmlValue
                            protected String value;
                            @XmlAttribute(name = "RegionCode")
                            protected String regionCode;

                            
                            public String getValue() {
                                return value;
                            }

                            
                            public void setValue(String value) {
                                this.value = value;
                            }

                            
                            public String getRegionCode() {
                                return regionCode;
                            }

                            
                            public void setRegionCode(String value) {
                                this.regionCode = value;
                            }

                        }

                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "category"
                    })
                    public static class ParticipantInfo {

                        @XmlElement(name = "Category", required = true)
                        protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category category;
                        @XmlAttribute(name = "available")
                        protected String available;

                        
                        public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category getCategory() {
                            return category;
                        }

                        
                        public void setCategory(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category value) {
                            this.category = value;
                        }

                        
                        public String getAvailable() {
                            return available;
                        }

                        
                        public void setAvailable(String value) {
                            this.available = value;
                        }


                        
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "qualifierInfo",
                            "contact"
                        })
                        public static class Category {

                            @XmlElement(name = "QualifierInfo", required = true)
                            protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category.QualifierInfo qualifierInfo;
                            @XmlElement(name = "Contact", required = true)
                            protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category.Contact contact;
                            @XmlAttribute(name = "Age")
                            protected String age;
                            @XmlAttribute(name = "ParticipantCategoryID")
                            protected String participantCategoryID;

                            
                            public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category.QualifierInfo getQualifierInfo() {
                                return qualifierInfo;
                            }

                            
                            public void setQualifierInfo(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category.QualifierInfo value) {
                                this.qualifierInfo = value;
                            }

                            
                            public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category.Contact getContact() {
                                return contact;
                            }

                            
                            public void setContact(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category.Contact value) {
                                this.contact = value;
                            }

                            
                            public String getAge() {
                                return age;
                            }

                            
                            public void setAge(String value) {
                                this.age = value;
                            }

                            
                            public String getParticipantCategoryID() {
                                return participantCategoryID;
                            }

                            
                            public void setParticipantCategoryID(String value) {
                                this.participantCategoryID = value;
                            }


                            
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "personName",
                                "telephone"
                            })
                            public static class Contact {

                                @XmlElement(name = "PersonName", required = true)
                                protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category.Contact.PersonName personName;
                                @XmlElement(name = "Telephone", required = true)
                                protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category.Contact.Telephone telephone;

                                
                                public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category.Contact.PersonName getPersonName() {
                                    return personName;
                                }

                                
                                public void setPersonName(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category.Contact.PersonName value) {
                                    this.personName = value;
                                }

                                
                                public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category.Contact.Telephone getTelephone() {
                                    return telephone;
                                }

                                
                                public void setTelephone(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.ParticipantInfo.Category.Contact.Telephone value) {
                                    this.telephone = value;
                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "givenName",
                                    "middleName",
                                    "surname"
                                })
                                public static class PersonName {

                                    @XmlElement(name = "GivenName", required = true)
                                    protected String givenName;
                                    @XmlElement(name = "MiddleName", required = true)
                                    protected String middleName;
                                    @XmlElement(name = "Surname", required = true)
                                    protected String surname;

                                    
                                    public String getGivenName() {
                                        return givenName;
                                    }

                                    
                                    public void setGivenName(String value) {
                                        this.givenName = value;
                                    }

                                    
                                    public String getMiddleName() {
                                        return middleName;
                                    }

                                    
                                    public void setMiddleName(String value) {
                                        this.middleName = value;
                                    }

                                    
                                    public String getSurname() {
                                        return surname;
                                    }

                                    
                                    public void setSurname(String value) {
                                        this.surname = value;
                                    }

                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "value"
                                })
                                public static class Telephone {

                                    @XmlValue
                                    protected String value;
                                    @XmlAttribute(name = "PhoneNumber")
                                    protected String phoneNumber;

                                    
                                    public String getValue() {
                                        return value;
                                    }

                                    
                                    public void setValue(String value) {
                                        this.value = value;
                                    }

                                    
                                    public String getPhoneNumber() {
                                        return phoneNumber;
                                    }

                                    
                                    public void setPhoneNumber(String value) {
                                        this.phoneNumber = value;
                                    }

                                }

                            }


                            
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "value"
                            })
                            public static class QualifierInfo {

                                @XmlValue
                                protected String value;
                                @XmlAttribute(name = "Extension")
                                protected String extension;

                                
                                public String getValue() {
                                    return value;
                                }

                                
                                public void setValue(String value) {
                                    this.value = value;
                                }

                                
                                public String getExtension() {
                                    return extension;
                                }

                                
                                public void setExtension(String value) {
                                    this.extension = value;
                                }

                            }

                        }

                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "value"
                    })
                    public static class PickupDropoff {

                        @XmlValue
                        protected String value;
                        @XmlAttribute(name = "available")
                        protected String available;
                        @XmlAttribute(name = "DateTime")
                        @XmlSchemaType(name = "dateTime")
                        protected XMLGregorianCalendar dateTime;
                        @XmlAttribute(name = "LocationName")
                        protected String locationName;
                        @XmlAttribute(name = "OtherInfo")
                        protected String otherInfo;

                        
                        public String getValue() {
                            return value;
                        }

                        
                        public void setValue(String value) {
                            this.value = value;
                        }

                        
                        public String getAvailable() {
                            return available;
                        }

                        
                        public void setAvailable(String value) {
                            this.available = value;
                        }

                        
                        public XMLGregorianCalendar getDateTime() {
                            return dateTime;
                        }

                        
                        public void setDateTime(XMLGregorianCalendar value) {
                            this.dateTime = value;
                        }

                        
                        public String getLocationName() {
                            return locationName;
                        }

                        
                        public void setLocationName(String value) {
                            this.locationName = value;
                        }

                        
                        public String getOtherInfo() {
                            return otherInfo;
                        }

                        
                        public void setOtherInfo(String value) {
                            this.otherInfo = value;
                        }

                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "summary",
                        "participantCategory"
                    })
                    public static class Pricing {

                        @XmlElement(name = "Summary", required = true)
                        protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.Summary summary;
                        @XmlElement(name = "ParticipantCategory", required = true)
                        protected List<CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.ParticipantCategory> participantCategory;
                        @XmlAttribute(name = "available")
                        protected String available;
                        @XmlAttribute(name = "PerPaxPriceInd")
                        protected String perPaxPriceInd;

                        
                        public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.Summary getSummary() {
                            return summary;
                        }

                        
                        public void setSummary(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.Summary value) {
                            this.summary = value;
                        }

                        
                        public List<CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.ParticipantCategory> getParticipantCategory() {
                            if (participantCategory == null) {
                                participantCategory = new ArrayList<CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.ParticipantCategory>();
                            }
                            return this.participantCategory;
                        }

                        
                        public String getAvailable() {
                            return available;
                        }

                        
                        public void setAvailable(String value) {
                            this.available = value;
                        }

                        
                        public String getPerPaxPriceInd() {
                            return perPaxPriceInd;
                        }

                        
                        public void setPerPaxPriceInd(String value) {
                            this.perPaxPriceInd = value;
                        }


                        
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "qualifierInfo",
                            "price"
                        })
                        public static class ParticipantCategory {

                            @XmlElement(name = "QualifierInfo", required = true)
                            protected String qualifierInfo;
                            @XmlElement(name = "Price", required = true)
                            protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.ParticipantCategory.Price price;

                            
                            public String getQualifierInfo() {
                                return qualifierInfo;
                            }

                            
                            public void setQualifierInfo(String value) {
                                this.qualifierInfo = value;
                            }

                            
                            public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.ParticipantCategory.Price getPrice() {
                                return price;
                            }

                            
                            public void setPrice(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.ParticipantCategory.Price value) {
                                this.price = value;
                            }


                            
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "value"
                            })
                            public static class Price {

                                @XmlValue
                                protected String value;
                                @XmlAttribute(name = "Amount")
                                protected Float amount;
                                @XmlAttribute(name = "CurrencyCode")
                                protected String currencyCode;

                                
                                public String getValue() {
                                    return value;
                                }

                                
                                public void setValue(String value) {
                                    this.value = value;
                                }

                                
                                public Float getAmount() {
                                    return amount;
                                }

                                
                                public void setAmount(Float value) {
                                    this.amount = value;
                                }

                                
                                public String getCurrencyCode() {
                                    return currencyCode;
                                }

                                
                                public void setCurrencyCode(String value) {
                                    this.currencyCode = value;
                                }

                            }

                        }


                        
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "taxAmounts"
                        })
                        public static class Summary {

                            @XmlElement(name = "TaxAmounts", required = true)
                            protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.Summary.TaxAmounts taxAmounts;
                            @XmlAttribute(name = "Amount")
                            protected Float amount;
                            @XmlAttribute(name = "CurrencyCode")
                            protected String currencyCode;

                            
                            public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.Summary.TaxAmounts getTaxAmounts() {
                                return taxAmounts;
                            }

                            
                            public void setTaxAmounts(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.Summary.TaxAmounts value) {
                                this.taxAmounts = value;
                            }

                            
                            public Float getAmount() {
                                return amount;
                            }

                            
                            public void setAmount(Float value) {
                                this.amount = value;
                            }

                            
                            public String getCurrencyCode() {
                                return currencyCode;
                            }

                            
                            public void setCurrencyCode(String value) {
                                this.currencyCode = value;
                            }


                            
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "taxAmount"
                            })
                            public static class TaxAmounts {

                                @XmlElement(name = "TaxAmount", required = true)
                                protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.Summary.TaxAmounts.TaxAmount taxAmount;
                                @XmlAttribute(name = "available")
                                protected String available;

                                
                                public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.Summary.TaxAmounts.TaxAmount getTaxAmount() {
                                    return taxAmount;
                                }

                                
                                public void setTaxAmount(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.Pricing.Summary.TaxAmounts.TaxAmount value) {
                                    this.taxAmount = value;
                                }

                                
                                public String getAvailable() {
                                    return available;
                                }

                                
                                public void setAvailable(String value) {
                                    this.available = value;
                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "value"
                                })
                                public static class TaxAmount {

                                    @XmlValue
                                    protected String value;
                                    @XmlAttribute(name = "Total")
                                    protected int total;
                                    @XmlAttribute(name = "TaxCode")
                                    protected String taxCode;
                                    @XmlAttribute(name = "Percentage")
                                    protected String percentage;

                                    
                                    public String getValue() {
                                        return value;
                                    }

                                    
                                    public void setValue(String value) {
                                        this.value = value;
                                    }

                                    
                                    public int getTotal() {
                                        return total;
                                    }

                                    
                                    public void setTotal(int value) {
                                        this.total = value;
                                    }

                                    
                                    public String getTaxCode() {
                                        return taxCode;
                                    }

                                    
                                    public void setTaxCode(String value) {
                                        this.taxCode = value;
                                    }

                                    
                                    public String getPercentage() {
                                        return percentage;
                                    }

                                    
                                    public void setPercentage(String value) {
                                        this.percentage = value;
                                    }

                                }

                            }

                        }

                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "value"
                    })
                    public static class Schedule {

                        @XmlValue
                        protected String value;
                        @XmlAttribute(name = "Start")
                        @XmlSchemaType(name = "dateTime")
                        protected XMLGregorianCalendar start;
                        @XmlAttribute(name = "End")
                        protected String end;

                        
                        public String getValue() {
                            return value;
                        }

                        
                        public void setValue(String value) {
                            this.value = value;
                        }

                        
                        public XMLGregorianCalendar getStart() {
                            return start;
                        }

                        
                        public void setStart(XMLGregorianCalendar value) {
                            this.start = value;
                        }

                        
                        public String getEnd() {
                            return end;
                        }

                        
                        public void setEnd(String value) {
                            this.end = value;
                        }

                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "activityTPA"
                    })
                    public static class TPAExtensions {

                        @XmlElement(name = "Activity_TPA", required = true)
                        protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions.ActivityTPA activityTPA;

                        
                        public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions.ActivityTPA getActivityTPA() {
                            return activityTPA;
                        }

                        
                        public void setActivityTPA(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions.ActivityTPA value) {
                            this.activityTPA = value;
                        }


                        
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "contactDetail"
                        })
                        public static class ActivityTPA {

                            @XmlElement(name = "ContactDetail", required = true)
                            protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions.ActivityTPA.ContactDetail contactDetail;

                            
                            public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions.ActivityTPA.ContactDetail getContactDetail() {
                                return contactDetail;
                            }

                            
                            public void setContactDetail(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions.ActivityTPA.ContactDetail value) {
                                this.contactDetail = value;
                            }


                            
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "personName",
                                "telephone"
                            })
                            public static class ContactDetail {

                                @XmlElement(name = "PersonName", required = true)
                                protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions.ActivityTPA.ContactDetail.PersonName personName;
                                @XmlElement(name = "Telephone", required = true)
                                protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions.ActivityTPA.ContactDetail.Telephone telephone;
                                @XmlAttribute(name = "available")
                                protected String available;

                                
                                public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions.ActivityTPA.ContactDetail.PersonName getPersonName() {
                                    return personName;
                                }

                                
                                public void setPersonName(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions.ActivityTPA.ContactDetail.PersonName value) {
                                    this.personName = value;
                                }

                                
                                public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions.ActivityTPA.ContactDetail.Telephone getTelephone() {
                                    return telephone;
                                }

                                
                                public void setTelephone(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.OTATourActivityResRetrieveRS.Detail.TPAExtensions.ActivityTPA.ContactDetail.Telephone value) {
                                    this.telephone = value;
                                }

                                
                                public String getAvailable() {
                                    return available;
                                }

                                
                                public void setAvailable(String value) {
                                    this.available = value;
                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "namePrefix",
                                    "givenName",
                                    "middleName",
                                    "surname"
                                })
                                public static class PersonName {

                                    @XmlElement(name = "NamePrefix", required = true)
                                    protected String namePrefix;
                                    @XmlElement(name = "GivenName", required = true)
                                    protected String givenName;
                                    @XmlElement(name = "MiddleName", required = true)
                                    protected String middleName;
                                    @XmlElement(name = "Surname", required = true)
                                    protected String surname;

                                    
                                    public String getNamePrefix() {
                                        return namePrefix;
                                    }

                                    
                                    public void setNamePrefix(String value) {
                                        this.namePrefix = value;
                                    }

                                    
                                    public String getGivenName() {
                                        return givenName;
                                    }

                                    
                                    public void setGivenName(String value) {
                                        this.givenName = value;
                                    }

                                    
                                    public String getMiddleName() {
                                        return middleName;
                                    }

                                    
                                    public void setMiddleName(String value) {
                                        this.middleName = value;
                                    }

                                    
                                    public String getSurname() {
                                        return surname;
                                    }

                                    
                                    public void setSurname(String value) {
                                        this.surname = value;
                                    }

                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "value"
                                })
                                public static class Telephone {

                                    @XmlValue
                                    protected String value;
                                    @XmlAttribute(name = "PhoneNumber")
                                    protected String phoneNumber;

                                    
                                    public String getValue() {
                                        return value;
                                    }

                                    
                                    public void setValue(String value) {
                                        this.value = value;
                                    }

                                    
                                    public String getPhoneNumber() {
                                        return phoneNumber;
                                    }

                                    
                                    public void setPhoneNumber(String value) {
                                        this.phoneNumber = value;
                                    }

                                }

                            }

                        }

                    }

                }

            }
            
            
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "error"
            })
            public static class ErrorList {
            	
            	@XmlElement(name = "Error", required = true)
                protected CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.ErrorList.Error error;

				public CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.ErrorList.Error getError() {
					return error;
				}

				public void setError(CommonRetrieveRS.ResponseBody.OTATourActivityResRetrieveRSIntWrapper.ErrorList.Error error) {
					this.error = error;
				}
            	
				@XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "errorCode",
                    "errorMsg",
                    "errorDetails"
                })
                public static class Error {

					@XmlElement(name = "ErrorCode")
                    protected String errorCode;
					@XmlElement(name = "ErrorMsg")
                    protected String errorMsg;
					@XmlElement(name = "ErrorDetails")
                    protected String errorDetails;
                    
                    
					public String getErrorCode() {
						return errorCode;
					}
					
					
					public void setErrorCode(String errorCode) {
						this.errorCode = errorCode;
					}
					
					
					public String getErrorMsg() {
						return errorMsg;
					}
					
					
					public void setErrorMsg(String errorMsg) {
						this.errorMsg = errorMsg;
					}
					
					
					public String getErrorDetails() {
						return errorDetails;
					}
					
					
					public void setErrorDetails(String errorDetails) {
						this.errorDetails = errorDetails;
					}

                }
            	
          }

        }
        
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "error"
        })
        public static class ErrorList {
        	
        	@XmlElement(name = "Error", required = true)
            protected CommonRetrieveRS.ResponseBody.ErrorList.Error error;

			public CommonRetrieveRS.ResponseBody.ErrorList.Error getError() {
				return error;
			}

			public void setError(CommonRetrieveRS.ResponseBody.ErrorList.Error error) {
				this.error = error;
			}
        	
			@XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "errorCode",
                "errorMsg",
                "errorDetails"
            })
            public static class Error {

				@XmlElement(name = "ErrorCode")
                protected String errorCode;
				@XmlElement(name = "ErrorMsg")
                protected String errorMsg;
				@XmlElement(name = "ErrorDetails")
                protected String errorDetails;
                
                
				public String getErrorCode() {
					return errorCode;
				}
				
				
				public void setErrorCode(String errorCode) {
					this.errorCode = errorCode;
				}
				
				
				public String getErrorMsg() {
					return errorMsg;
				}
				
				
				public void setErrorMsg(String errorMsg) {
					this.errorMsg = errorMsg;
				}
				
				
				public String getErrorDetails() {
					return errorDetails;
				}
				
				
				public void setErrorDetails(String errorDetails) {
					this.errorDetails = errorDetails;
				}

            }

        }

    }


    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "status",
        "userID",
        "sessionID",
        "transactionID"
    })
    public static class ResponseHeader {

        @XmlElement(name = "Status", required = true)
        protected String status;
        @XmlElement(name = "UserID", required = true)
        protected String userID;
        @XmlElement(name = "SessionID", required = true)
        protected String sessionID;
        @XmlElement(name = "TransactionID")
        protected short transactionID;

        
        public String getStatus() {
            return status;
        }

        
        public void setStatus(String value) {
            this.status = value;
        }

        
        public String getUserID() {
            return userID;
        }

        
        public void setUserID(String value) {
            this.userID = value;
        }

        
        public String getSessionID() {
            return sessionID;
        }

        
        public void setSessionID(String value) {
            this.sessionID = value;
        }

        
        public short getTransactionID() {
            return transactionID;
        }

        
        public void setTransactionID(short value) {
            this.transactionID = value;
        }

    }

}
