//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.12 at 04:35:10 PM IST 
//


package com.cnk.siapi.response;

import javax.xml.bind.annotation.XmlRegistry;



@XmlRegistry
public class CommonRepriceObjectFactory {


    
    public CommonRepriceObjectFactory() {
    }

    
    public CommonRepriceRS createCommonRepriceRS() {
        return new CommonRepriceRS();
    }

    
    public CommonRepriceRS.ResponseBody createCommonRepriceRSResponseBody() {
        return new CommonRepriceRS.ResponseBody();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapper() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper();
    }

    
    public CommonRepriceRS.ResponseBody.ErrorList createCommonRepriceRSResponseBodyErrorList() {
        return new CommonRepriceRS.ResponseBody.ErrorList();
    }
    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRS() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.ErrorList createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperErrorList() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.ErrorList();
    }
    
    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.ErrorList.Error createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperErrorListError() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.ErrorList.Error();
    }
    
    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfo() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoPricing() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.ParticipantCategory createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoPricingParticipantCategory() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.ParticipantCategory();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.Summary createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoPricingSummary() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.Summary();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.Summary.TaxAmounts createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoPricingSummaryTaxAmounts() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.Summary.TaxAmounts();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoLocation() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location.Address createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoLocationAddress() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location.Address();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Extras createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoExtras() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Extras();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoSchedule() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule.Detail createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoScheduleDetail() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule.Detail();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule.Detail.OperationTimes createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoScheduleDetailOperationTimes() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule.Detail.OperationTimes();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfo() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensions() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPA() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Addons createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPAAddons() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Addons();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Questions createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPAQuestions() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Questions();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.TimeSlots createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPATimeSlots() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.TimeSlots();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Participants createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPAParticipant() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Participants();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.ShippingDetails createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPAShippingDetails() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.ShippingDetails();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.ShippingDetails.ShippingAreas createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPAShippingDetailsShippingAreas() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.ShippingDetails.ShippingAreas();
    }

    
    public CommonRepriceRS.ResponseHeader createCommonRepriceRSResponseHeader() {
        return new CommonRepriceRS.ResponseHeader();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Description createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoDescription() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Description();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.ParticipantCategory.QualifierInfo createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoPricingParticipantCategoryQualifierInfo() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.ParticipantCategory.QualifierInfo();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.ParticipantCategory.Price createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoPricingParticipantCategoryPrice() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.ParticipantCategory.Price();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.Summary.TaxAmounts.TaxAmount createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoPricingSummaryTaxAmountsTaxAmount() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.Summary.TaxAmounts.TaxAmount();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location.Region createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoLocationRegion() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location.Region();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location.Address.CountryName createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoLocationAddressCountryName() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location.Address.CountryName();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Extras.Extra createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoExtrasExtra() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Extras.Extra();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule.Detail.OperationTimes.OperationTime createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoScheduleDetailOperationTimesOperationTime() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule.Detail.OperationTimes.OperationTime();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.SupplierDetails createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPASupplierDetails() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.SupplierDetails();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.TourLanguage createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPATourLanguage() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.TourLanguage();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Vouchers createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPAVouchers() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Vouchers();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Addons.Addon createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPAAddonsAddon() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Addons.Addon();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Questions.Question createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPAQuestionsQuestion() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Questions.Question();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.TimeSlots.TimeSlot createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPATimeSlotsTimeSlot() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.TimeSlots.TimeSlot();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Participants.Participant.QualifierInfo createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPAParticipantsParticipantsParticipantQualifierInfo() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Participants.Participant.QualifierInfo();
    }

    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Participants.Participant createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPAParticipantsParticipant() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Participants.Participant();
    }
    
    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.ShippingDetails.ShippingAreas.RateList createCommonRepriceRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPAShippingDetailsShippingAreasRateList() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.ShippingDetails.ShippingAreas.RateList();
    }

    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.Errors createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSErrors() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.Errors();
    }
    
    
    public CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.Errors.Error createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSErrorsError() {
        return new CommonRepriceRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.Errors.Error();
    }
    
}
