//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.12 at 04:34:26 PM IST 
//


package com.cnk.siapi.response;

import javax.xml.bind.annotation.XmlRegistry;



@XmlRegistry
public class CommonGetDetailsObjectFactory {


    
    public CommonGetDetailsObjectFactory() {
    }

    
    public CommonGetDetailsRS createCommonGetDetailsRS() {
        return new CommonGetDetailsRS();
    }

    
    public CommonGetDetailsRS.ResponseBody createCommonGetDetailsRSResponseBody() {
        return new CommonGetDetailsRS.ResponseBody();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapper() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper();
    }
    
    public CommonGetDetailsRS.ResponseBody.ErrorList createCommonGetDetailsRSResponseBodyErrorList() {
        return new CommonGetDetailsRS.ResponseBody.ErrorList();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRS() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.ErrorList createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperErrorList() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.ErrorList();
    }
    
    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfo() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo();
    }


    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.ErrorList.Error createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperErrorListError() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.ErrorList.Error();
    }
    
    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.ProductOptions createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoProductOptions() {
    	return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.ProductOptions();
    }
    
    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoPricing() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.ParticipantCategory createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoPricingParticipantCategory() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.ParticipantCategory();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.Summary createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoPricingSummary() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.Summary();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.Summary.TaxAmounts createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoPricingSummaryTaxAmounts() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.Summary.TaxAmounts();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoLocation() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location.Address createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoLocationAddress() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location.Address();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Extras createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoExtras() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Extras();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoSchedule() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule.Detail createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoScheduleDetail() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule.Detail();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule.Detail.OperationTimes createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoScheduleDetailOperationTimes() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule.Detail.OperationTimes();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfo() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensions() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPA() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA();
    }

    
    public MultiSearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Addons createMultiSearchRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPAAddons() {
        return new MultiSearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Addons();
    }
    
    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.TimeSlots createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPATimeSlots() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.TimeSlots();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Participants createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPAParticipant() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Participants();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.ShippingDetails createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPAShippingDetails() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.ShippingDetails();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.ShippingDetails.ShippingAreas createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPAShippingDetailsShippingAreas() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.ShippingDetails.ShippingAreas();
    }

    
    public CommonGetDetailsRS.ResponseHeader createCommonGetDetailsRSResponseHeader() {
        return new CommonGetDetailsRS.ResponseHeader();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Description createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoDescription() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Description();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.ParticipantCategory.QualifierInfo createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoPricingParticipantCategoryQualifierInfo() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.ParticipantCategory.QualifierInfo();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.ParticipantCategory.Price createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoPricingParticipantCategoryPrice() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.ParticipantCategory.Price();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.Summary.TaxAmounts.TaxAmount createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoPricingSummaryTaxAmountsTaxAmount() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.Summary.TaxAmounts.TaxAmount();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location.Region createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoLocationRegion() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location.Region();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location.Address.CountryName createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoLocationAddressCountryName() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location.Address.CountryName();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Extras.Extra createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoExtrasExtra() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Extras.Extra();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule.Detail.OperationTimes.OperationTime createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoScheduleDetailOperationTimesOperationTime() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule.Detail.OperationTimes.OperationTime();
    }

    
    public MultiSearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Addons.Addon createMultiSearchRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPAAddonsAddon() {
        return new MultiSearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Addons.Addon();
    }
    
    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.SupplierDetails createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPASupplierDetails() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.SupplierDetails();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.TourLanguage createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPATourLanguage() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.TourLanguage();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Vouchers createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPAVouchers() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Vouchers();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Questions createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPAQuestions() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Questions();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.TimeSlots.TimeSlot createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPATimeSlotsTimeSlot() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.TimeSlots.TimeSlot();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Participants.Participant.QualifierInfo createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPAParticipantsParticipantQualifierInfo() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Participants.Participant.QualifierInfo();
    }
    
    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Participants.Participant createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPAParticipantsParticipant() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Participants.Participant();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.ShippingDetails.ShippingAreas.RateList createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoBasicInfoTPAExtensionsActivityTPAShippingDetailsShippingareasRateList() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.ShippingDetails.ShippingAreas.RateList();
    }

    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.Errors createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSErrors() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.Errors();
    }
    
    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.Errors.Error createCommonCancelRSResponseBodyOTATourActivityCancelRSWrapperOTATourActivityCancelRSErrorsError() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.Errors.Error();
    }
    
    public CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.ProductOptions.ProductOption createCommonGetDetailsRSResponseBodyOTATourActivityAvailRSWrapperOTATourActivityAvailRSTourActivityInfoProductOptionsProductOption() {
        return new CommonGetDetailsRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.ProductOptions.ProductOption();
    }
}
