//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.12 at 04:34:46 PM IST 
//


package com.cnk.siapi.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responseHeader",
    "responseBody"
})
@XmlRootElement(name = "SightSeeingInterfaceRS")
public class CommonGetPolicyRS {

    @XmlElement(name = "ResponseHeader", required = true)
    protected CommonGetPolicyRS.ResponseHeader responseHeader;
    @XmlElement(name = "ResponseBody", required = true)
    protected CommonGetPolicyRS.ResponseBody responseBody;

    
    public CommonGetPolicyRS.ResponseHeader getResponseHeader() {
        return responseHeader;
    }

    
    public void setResponseHeader(CommonGetPolicyRS.ResponseHeader value) {
        this.responseHeader = value;
    }

    
    public CommonGetPolicyRS.ResponseBody getResponseBody() {
        return responseBody;
    }

    
    public void setResponseBody(CommonGetPolicyRS.ResponseBody value) {
        this.responseBody = value;
    }


    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
    	"cnkStatus",
        "otaTourActivityCancellationPoliciesRSWrapper",
        "errorList"
    })
    public static class ResponseBody {

    	@XmlElement(name = "CNKStatus", required = true)
        protected String cnkStatus;
        @XmlElement(name = "OTA_TourActivityCancellationPoliciesRSWrapper", required = true)
        protected CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper otaTourActivityCancellationPoliciesRSWrapper;
        @XmlElement(name = "ErrorList", required = true)
        protected CommonGetPolicyRS.ResponseBody.ErrorList errorList;

        
        public String getCnkStatus() {
			return cnkStatus;
		}


		public void setCnkStatus(String cnkStatus) {
			this.cnkStatus = cnkStatus;
		}


		public CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper getOTATourActivityCancellationPoliciesRSWrapper() {
            return otaTourActivityCancellationPoliciesRSWrapper;
        }

        
        public void setOTATourActivityCancellationPoliciesRSWrapper(CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper value) {
            this.otaTourActivityCancellationPoliciesRSWrapper = value;
        }

        
        public CommonGetPolicyRS.ResponseBody.ErrorList getErrorList() {
			return errorList;
		}


		public void setErrorList(CommonGetPolicyRS.ResponseBody.ErrorList errorList) {
			this.errorList = errorList;
		}


		@XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "supplierID",
            "accessCode",
            "otaTourActivityCancellationPoliciesRS",
            "errorList"
        })
        public static class OTATourActivityCancellationPoliciesRSWrapper {

            @XmlElement(name = "SupplierID", required = true)
            protected String supplierID;
            @XmlElement(name = "Sequence")
            protected String accessCode;
            @XmlElement(name = "OTA_TourActivityCancellationPoliciesRS", required = true)
            protected CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.OTATourActivityCancellationPoliciesRS otaTourActivityCancellationPoliciesRS;
            @XmlElement(name = "ErrorList", required = true)
            protected CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.ErrorList errorList;
            
            
            public String getSupplierID() {
                return supplierID;
            }

            
            public void setSupplierID(String value) {
                this.supplierID = value;
            }

            
            public String getAccessCode() {
                return accessCode;
            }

            
            public void setAccessCode(String value) {
                this.accessCode = value;
            }

            
            public CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.OTATourActivityCancellationPoliciesRS getOTATourActivityCancellationPoliciesRS() {
                return otaTourActivityCancellationPoliciesRS;
            }

            
            public void setOTATourActivityCancellationPoliciesRS(CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.OTATourActivityCancellationPoliciesRS value) {
                this.otaTourActivityCancellationPoliciesRS = value;
            }
            
            
            public CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.ErrorList getErrorList() {
				return errorList;
			}


			public void setErrorList(CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.ErrorList errorList) {
				this.errorList = errorList;
			}
            
            
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "cancellationPolicies"
            })
            public static class OTATourActivityCancellationPoliciesRS {

                @XmlElement(name = "CancellationPolicies")
                protected List<CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.OTATourActivityCancellationPoliciesRS.CancellationPolicies> cancellationPolicies;

                
                public List<CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.OTATourActivityCancellationPoliciesRS.CancellationPolicies> getCancellationPolicies() {
                    if (cancellationPolicies == null) {
                        cancellationPolicies = new ArrayList<CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.OTATourActivityCancellationPoliciesRS.CancellationPolicies>();
                    }
                    return this.cancellationPolicies;
                }


                
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "fromValue",
                    "toValue",
                    "currencyCode",
                    "supplierProductCode",
                    "referenceCode",
                    "rate",
                    "requestedCurrencyCode",
                    "convertedRate",
                    "text",
                    "unit",
                    "chargeType",
                    "ckisText"
                })
                public static class CancellationPolicies {

                    @XmlElement(name = "FromValue")
                    protected String fromValue;
                    @XmlElement(name = "ToValue", required = true)
                    protected String toValue;
                    @XmlElement(name = "CurrencyCode", required = true)
                    protected String currencyCode;
                    @XmlElement(name = "RequestedCurrencyCode", required = true)
                    protected String requestedCurrencyCode;
                    @XmlElement(name = "SupplierProductCode")
                    protected Integer supplierProductCode;
                    @XmlElement(name = "ReferenceCode")
                    protected String referenceCode;
                    @XmlElement(name = "Rate")
                    protected String rate;
                    @XmlElement(name = "ConvertedRate")
                    protected String convertedRate;
                    @XmlElement(name = "Text", required = true)
                    protected String text;
                    @XmlElement(name = "CKISText", required = true)
                    protected String ckisText;     
                    @XmlElement(name = "Unit", required = true)
                    protected String unit;
                    @XmlElement(name = "ChargeType", required = true)
                    protected String chargeType;
              
                    public String getFromValue() {
                        return fromValue;
                    }
    
                    public String getCkisText() {
						return ckisText;
					}

					public void setCkisText(String ckisText) {
						this.ckisText = ckisText;
					}



					public void setFromValue(String value) {
                        this.fromValue = value;
                    }

                    
                    public String getToValue() {
                        return toValue;
                    }

                    
                    public void setToValue(String value) {
                        this.toValue = value;
                    }

                    
                    public String getCurrencyCode() {
                        return currencyCode;
                    }

                    
                    public void setCurrencyCode(String value) {
                        this.currencyCode = value;
                    }

                    
                    public Integer getSupplierProductCode() {
                        return supplierProductCode;
                    }

                    
                    public void setSupplierProductCode(Integer value) {
                        this.supplierProductCode = value;
                    }

                    
                    public String getReferenceCode() {
                        return referenceCode;
                    }

                    
                    public void setReferenceCode(String value) {
                        this.referenceCode = value;
                    }

                    
                    public String getRate() {
                        return rate;
                    }

                    
                    public void setRate(String value) {
                        this.rate = value;
                    }

                    
                    public String getText() {
                        return text;
                    }

                    
                    public void setText(String value) {
                        this.text = value;
                    }

                    
                    public String getUnit() {
                        return unit;
                    }

                    
                    public void setUnit(String value) {
                        this.unit = value;
                    }

                    
                    public String getChargeType() {
                        return chargeType;
                    }

                    
                    public void setChargeType(String value) {
                        this.chargeType = value;
                    }

					public String getRequestedCurrencyCode() {
						return requestedCurrencyCode;
					}

					public void setRequestedCurrencyCode(String requestedCurrencyCode) {
						this.requestedCurrencyCode = requestedCurrencyCode;
					}

					public String getConvertedRate() {
						return convertedRate;
					}

					public void setConvertedRate(String convertedRate) {
						this.convertedRate = convertedRate;
					}
                    
                }

            }
            
            
            
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "error"
            })
            public static class ErrorList {
            	
            	@XmlElement(name = "Error", required = true)
                protected CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.ErrorList.Error error;

				public CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.ErrorList.Error getError() {
					return error;
				}

				public void setError(CommonGetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.ErrorList.Error error) {
					this.error = error;
				}
            	
				@XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "errorCode",
                    "errorMsg",
                    "errorDetails"
                })
                public static class Error {

					@XmlElement(name = "ErrorCode")
                    protected String errorCode;
					@XmlElement(name = "ErrorMsg")
                    protected String errorMsg;
					@XmlElement(name = "ErrorDetails")
                    protected String errorDetails;
                    
                    
					public String getErrorCode() {
						return errorCode;
					}
					
					
					public void setErrorCode(String errorCode) {
						this.errorCode = errorCode;
					}
					
					
					public String getErrorMsg() {
						return errorMsg;
					}
					
					
					public void setErrorMsg(String errorMsg) {
						this.errorMsg = errorMsg;
					}
					
					
					public String getErrorDetails() {
						return errorDetails;
					}
					
					
					public void setErrorDetails(String errorDetails) {
						this.errorDetails = errorDetails;
					}

                }
            	
          }

            
        }
        
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "error"
        })
        public static class ErrorList {
        	
        	@XmlElement(name = "Error", required = true)
            protected CommonGetPolicyRS.ResponseBody.ErrorList.Error error;

			public CommonGetPolicyRS.ResponseBody.ErrorList.Error getError() {
				return error;
			}

			public void setError(CommonGetPolicyRS.ResponseBody.ErrorList.Error error) {
				this.error = error;
			}
        	
			@XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "errorCode",
                "errorMsg",
                "errorDetails"
            })
            public static class Error {

				@XmlElement(name = "ErrorCode")
                protected String errorCode;
				@XmlElement(name = "ErrorMsg")
                protected String errorMsg;
				@XmlElement(name = "ErrorDetails")
                protected String errorDetails;
                
                
				public String getErrorCode() {
					return errorCode;
				}
				
				
				public void setErrorCode(String errorCode) {
					this.errorCode = errorCode;
				}
				
				
				public String getErrorMsg() {
					return errorMsg;
				}
				
				
				public void setErrorMsg(String errorMsg) {
					this.errorMsg = errorMsg;
				}
				
				
				public String getErrorDetails() {
					return errorDetails;
				}
				
				
				public void setErrorDetails(String errorDetails) {
					this.errorDetails = errorDetails;
				}

            }
        	

      }

    }


    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "status",
        "userID",
        "sessionID",
        "transactionID"
    })
    public static class ResponseHeader {

        @XmlElement(name = "Status", required = true)
        protected String status;
        @XmlElement(name = "UserID", required = true)
        protected String userID;
        @XmlElement(name = "SessionID", required = true)
        protected String sessionID;
        @XmlElement(name = "TransactionID", required = true)
        protected String transactionID;

        
        public String getStatus() {
            return status;
        }

        
        public void setStatus(String value) {
            this.status = value;
        }

        
        public String getUserID() {
            return userID;
        }

        
        public void setUserID(String value) {
            this.userID = value;
        }

        
        public String getSessionID() {
            return sessionID;
        }

        
        public void setSessionID(String value) {
            this.sessionID = value;
        }

        
        public String getTransactionID() {
            return transactionID;
        }

        
        public void setTransactionID(String value) {
            this.transactionID = value;
        }

    }

}
