//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.02 at 11:55:07 AM IST 
//


package com.cnk.siapi.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responseHeader",
    "responseBody"
})
@XmlRootElement(name = "SightSeeingInterfaceRS")
public class GetPolicyRS {

    @XmlElement(name = "ResponseHeader", required = true)
    protected GetPolicyRS.ResponseHeader responseHeader;
    @XmlElement(name = "ResponseBody", required = true)
    protected GetPolicyRS.ResponseBody responseBody;

    
    public GetPolicyRS.ResponseHeader getResponseHeader() {
        return responseHeader;
    }

    
    public void setResponseHeader(GetPolicyRS.ResponseHeader value) {
        this.responseHeader = value;
    }

    
    public GetPolicyRS.ResponseBody getResponseBody() {
        return responseBody;
    }

    
    public void setResponseBody(GetPolicyRS.ResponseBody value) {
        this.responseBody = value;
    }


    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "otaTourActivityCancellationPoliciesRSWrapper"
    })
    public static class ResponseBody {

        @XmlElement(name = "OTA_TourActivityCancellationPoliciesRSWrapper", required = true)
        protected GetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper otaTourActivityCancellationPoliciesRSWrapper;

        
        public GetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper getOTATourActivityCancellationPoliciesRSWrapper() {
            return otaTourActivityCancellationPoliciesRSWrapper;
        }

        
        public void setOTATourActivityCancellationPoliciesRSWrapper(GetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper value) {
            this.otaTourActivityCancellationPoliciesRSWrapper = value;
        }


        
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "supplierID",
            "sequence",
            "otaTourActivityCancellationPoliciesRS"
        })
        public static class OTATourActivityCancellationPoliciesRSWrapper {

            @XmlElement(name = "SupplierID", required = true)
            protected String supplierID;
            @XmlElement(name = "Sequence")
            protected Integer sequence;
            @XmlElement(name = "OTA_TourActivityCancellationPoliciesRS", required = true)
            protected GetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.OTATourActivityCancellationPoliciesRS otaTourActivityCancellationPoliciesRS;

            
            public String getSupplierID() {
                return supplierID;
            }

            
            public void setSupplierID(String value) {
                this.supplierID = value;
            }

            
            public Integer getSequence() {
                return sequence;
            }

            
            public void setSequence(Integer value) {
                this.sequence = value;
            }

            
            public GetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.OTATourActivityCancellationPoliciesRS getOTATourActivityCancellationPoliciesRS() {
                return otaTourActivityCancellationPoliciesRS;
            }

            
            public void setOTATourActivityCancellationPoliciesRS(GetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.OTATourActivityCancellationPoliciesRS value) {
                this.otaTourActivityCancellationPoliciesRS = value;
            }


            
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "cancellationPolicies"
            })
            public static class OTATourActivityCancellationPoliciesRS {

                @XmlElement(name = "CancellationPolicies", required = true)
                protected GetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.OTATourActivityCancellationPoliciesRS.CancellationPolicies cancellationPolicies;

                
                public GetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.OTATourActivityCancellationPoliciesRS.CancellationPolicies getCancellationPolicies() {
                    return cancellationPolicies;
                }

                
                public void setCancellationPolicies(GetPolicyRS.ResponseBody.OTATourActivityCancellationPoliciesRSWrapper.OTATourActivityCancellationPoliciesRS.CancellationPolicies value) {
                    this.cancellationPolicies = value;
                }


                
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "fromValue",
                    "toValue",
                    "currencyCode",
                    "supplierProductCode",
                    "referenceCode",
                    "rate",
                    "text",
                    "unit",
                    "chargeType"
                })
                public static class CancellationPolicies {

                    @XmlElement(name = "FromValue")
                    protected Integer fromValue;
                    @XmlElement(name = "ToValue", required = true)
                    protected String toValue;
                    @XmlElement(name = "CurrencyCode", required = true)
                    protected String currencyCode;
                    @XmlElement(name = "SupplierProductCode")
                    protected Integer supplierProductCode;
                    @XmlElement(name = "ReferenceCode")
                    protected String referenceCode;
                    @XmlElement(name = "Rate")
                    protected Integer rate;
                    @XmlElement(name = "Text", required = true)
                    protected String text;
                    @XmlElement(name = "Unit", required = true)
                    protected String unit;
                    @XmlElement(name = "ChargeType", required = true)
                    protected String chargeType;

                    
                    public Integer getFromValue() {
                        return fromValue;
                    }

                    
                    public void setFromValue(Integer value) {
                        this.fromValue = value;
                    }

                    
                    public String getToValue() {
                        return toValue;
                    }

                    
                    public void setToValue(String value) {
                        this.toValue = value;
                    }

                    
                    public String getCurrencyCode() {
                        return currencyCode;
                    }

                    
                    public void setCurrencyCode(String value) {
                        this.currencyCode = value;
                    }

                    
                    public Integer getSupplierProductCode() {
                        return supplierProductCode;
                    }

                    
                    public void setSupplierProductCode(Integer value) {
                        this.supplierProductCode = value;
                    }

                    
                    public String getReferenceCode() {
                        return referenceCode;
                    }

                    
                    public void setReferenceCode(String value) {
                        this.referenceCode = value;
                    }

                    
                    public Integer getRate() {
                        return rate;
                    }

                    
                    public void setRate(Integer value) {
                        this.rate = value;
                    }

                    
                    public String getText() {
                        return text;
                    }

                    
                    public void setText(String value) {
                        this.text = value;
                    }

                    
                    public String getUnit() {
                        return unit;
                    }

                    
                    public void setUnit(String value) {
                        this.unit = value;
                    }

                    
                    public String getChargeType() {
                        return chargeType;
                    }

                    
                    public void setChargeType(String value) {
                        this.chargeType = value;
                    }

                }

            }

        }

    }


    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "status",
        "userID",
        "sessionID",
        "transactionID"
    })
    public static class ResponseHeader {

        @XmlElement(name = "Status", required = true)
        protected String status;
        @XmlElement(name = "UserID", required = true)
        protected String userID;
        @XmlElement(name = "SessionID", required = true)
        protected String sessionID;
        @XmlElement(name = "TransactionID", required = true)
        protected String transactionID;

        
        public String getStatus() {
            return status;
        }

        
        public void setStatus(String value) {
            this.status = value;
        }

        
        public String getUserID() {
            return userID;
        }

        
        public void setUserID(String value) {
            this.userID = value;
        }

        
        public String getSessionID() {
            return sessionID;
        }

        
        public void setSessionID(String value) {
            this.sessionID = value;
        }

        
        public String getTransactionID() {
            return transactionID;
        }

        
        public void setTransactionID(String value) {
            this.transactionID = value;
        }

    }

}
