//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.23 at 10:59:40 AM IST 
//


package com.cnk.siapi.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responseHeader",
    "responseBody"
})
@XmlRootElement(name = "SightSeeingInterfaceRS")
public class SearchRS {

    @XmlElement(name = "ResponseHeader", required = true)
    protected SearchRS.ResponseHeader responseHeader;
    @XmlElement(name = "ResponseBody", required = true)
    protected SearchRS.ResponseBody responseBody;

    
    public SearchRS.ResponseHeader getResponseHeader() {
        return responseHeader;
    }

    
    public void setResponseHeader(SearchRS.ResponseHeader value) {
        this.responseHeader = value;
    }

    
    public SearchRS.ResponseBody getResponseBody() {
        return responseBody;
    }

    
    public void setResponseBody(SearchRS.ResponseBody value) {
        this.responseBody = value;
    }


    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "otaTourActivityAvailRSWrapper"
    })
    public static class ResponseBody {

        @XmlElement(name = "OTA_TourActivityAvailRSWrapper", required = true)
        protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper otaTourActivityAvailRSWrapper;

        
        public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper getOTATourActivityAvailRSWrapper() {
            return otaTourActivityAvailRSWrapper;
        }

        
        public void setOTATourActivityAvailRSWrapper(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper value) {
            this.otaTourActivityAvailRSWrapper = value;
        }


        
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "supplierID",
            "sequence",
            "otaTourActivityAvailRS"
        })
        public static class OTATourActivityAvailRSWrapper {

            @XmlElement(name = "SupplierID", required = true)
            protected String supplierID;
            @XmlElement(name = "Sequence")
            protected Integer sequence;
            @XmlElement(name = "OTA_TourActivityAvailRS", required = true)
            protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS otaTourActivityAvailRS;

            
            public String getSupplierID() {
                return supplierID;
            }

            
            public void setSupplierID(String value) {
                this.supplierID = value;
            }

            
            public Integer getSequence() {
                return sequence;
            }

            
            public void setSequence(Integer value) {
                this.sequence = value;
            }

            
            public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS getOTATourActivityAvailRS() {
                return otaTourActivityAvailRS;
            }

            
            public void setOTATourActivityAvailRS(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS value) {
                this.otaTourActivityAvailRS = value;
            }


            
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "success",
                "tourActivityInfo"
            })
            public static class OTATourActivityAvailRS {

                @XmlElement(name = "Success", required = true)
                protected String success;
                @XmlElement(name = "TourActivityInfo")
                protected List<SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo> tourActivityInfo;

                
                public String getSuccess() {
                    return success;
                }

                
                public void setSuccess(String value) {
                    this.success = value;
                }

                
                public List<SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo> getTourActivityInfo() {
                    if (tourActivityInfo == null) {
                        tourActivityInfo = new ArrayList<SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo>();
                    }
                    return this.tourActivityInfo;
                }


                
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "basicInfo",
                    "schedule",
                    "description",
                    "extra",
                    "location",
                    "pricing"
                })
                public static class TourActivityInfo {

                    @XmlElement(name = "BasicInfo", required = true)
                    protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo basicInfo;
                    @XmlElement(name = "Schedule", required = true)
                    protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule schedule;
                    @XmlElement(name = "Description", required = true)
                    protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Description description;
                    @XmlElement(name = "Extra", required = true)
                    protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Extra extra;
                    @XmlElement(name = "Location", required = true)
                    protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location location;
                    @XmlElement(name = "Pricing", required = true)
                    protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing pricing;

                    
                    public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo getBasicInfo() {
                        return basicInfo;
                    }

                    
                    public void setBasicInfo(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo value) {
                        this.basicInfo = value;
                    }

                    
                    public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule getSchedule() {
                        return schedule;
                    }

                    
                    public void setSchedule(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule value) {
                        this.schedule = value;
                    }

                    
                    public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Description getDescription() {
                        return description;
                    }

                    
                    public void setDescription(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Description value) {
                        this.description = value;
                    }

                    
                    public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Extra getExtra() {
                        return extra;
                    }

                    
                    public void setExtra(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Extra value) {
                        this.extra = value;
                    }

                    
                    public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location getLocation() {
                        return location;
                    }

                    
                    public void setLocation(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location value) {
                        this.location = value;
                    }

                    
                    public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing getPricing() {
                        return pricing;
                    }

                    
                    public void setPricing(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing value) {
                        this.pricing = value;
                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "tpaExtensions"
                    })
                    public static class BasicInfo {

                        @XmlElement(name = "TPA_Extensions", required = true)
                        protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions tpaExtensions;
                        @XmlAttribute(name = "SupplierProductCode")
                        protected Integer supplierProductCode;
                        @XmlAttribute(name = "Name")
                        protected String name;
                        @XmlAttribute(name = "ShortName")
                        protected String shortName;
                        @XmlAttribute(name = "SupplierBrandCode")
                        protected String supplierBrandCode;

                        
                        public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions getTPAExtensions() {
                            return tpaExtensions;
                        }

                        
                        public void setTPAExtensions(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions value) {
                            this.tpaExtensions = value;
                        }

                        
                        public Integer getSupplierProductCode() {
                            return supplierProductCode;
                        }

                        
                        public void setSupplierProductCode(Integer value) {
                            this.supplierProductCode = value;
                        }

                        
                        public String getName() {
                            return name;
                        }

                        
                        public void setName(String value) {
                            this.name = value;
                        }

                        
                        public String getShortName() {
                            return shortName;
                        }

                        
                        public void setShortName(String value) {
                            this.shortName = value;
                        }

                        
                        public String getSupplierBrandCode() {
                            return supplierBrandCode;
                        }

                        
                        public void setSupplierBrandCode(String value) {
                            this.supplierBrandCode = value;
                        }


                        
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "activityTPA"
                        })
                        public static class TPAExtensions {

                            @XmlElement(name = "Activity_TPA", required = true)
                            protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA activityTPA;

                            
                            public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA getActivityTPA() {
                                return activityTPA;
                            }

                            
                            public void setActivityTPA(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA value) {
                                this.activityTPA = value;
                            }


                            
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "availabilityStatus",
                                "shippingDetails",
                                "participant",
                                "supplierDetails",
                                "tourLanguage",
                                "timeSlots",
                                "vouchers",
                                "questions"
                            })
                            public static class ActivityTPA {

                                @XmlElement(name = "Availability_Status", required = true)
                                protected String availabilityStatus;
                                @XmlElement(name = "Shipping_Details", required = true)
                                protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.ShippingDetails shippingDetails;
                                @XmlElement(name = "Participant", required = true)
                                protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Participant participant;
                                @XmlElement(name = "Supplier_Details", required = true)
                                protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.SupplierDetails supplierDetails;
                                @XmlElement(name = "TourLanguage", required = true)
                                protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.TourLanguage tourLanguage;
                                @XmlElement(name = "TimeSlots", required = true)
                                protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.TimeSlots timeSlots;
                                @XmlElement(name = "Vouchers", required = true)
                                protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Vouchers vouchers;
                                @XmlElement(name = "Questions", required = true)
                                protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Questions questions;

                                
                                public String getAvailabilityStatus() {
                                    return availabilityStatus;
                                }

                                
                                public void setAvailabilityStatus(String value) {
                                    this.availabilityStatus = value;
                                }

                                
                                public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.ShippingDetails getShippingDetails() {
                                    return shippingDetails;
                                }

                                
                                public void setShippingDetails(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.ShippingDetails value) {
                                    this.shippingDetails = value;
                                }

                                
                                public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Participant getParticipant() {
                                    return participant;
                                }

                                
                                public void setParticipant(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Participant value) {
                                    this.participant = value;
                                }

                                
                                public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.SupplierDetails getSupplierDetails() {
                                    return supplierDetails;
                                }

                                
                                public void setSupplierDetails(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.SupplierDetails value) {
                                    this.supplierDetails = value;
                                }

                                
                                public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.TourLanguage getTourLanguage() {
                                    return tourLanguage;
                                }

                                
                                public void setTourLanguage(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.TourLanguage value) {
                                    this.tourLanguage = value;
                                }

                                
                                public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.TimeSlots getTimeSlots() {
                                    return timeSlots;
                                }

                                
                                public void setTimeSlots(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.TimeSlots value) {
                                    this.timeSlots = value;
                                }

                                
                                public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Vouchers getVouchers() {
                                    return vouchers;
                                }

                                
                                public void setVouchers(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Vouchers value) {
                                    this.vouchers = value;
                                }

                                
                                public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Questions getQuestions() {
                                    return questions;
                                }

                                
                                public void setQuestions(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Questions value) {
                                    this.questions = value;
                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "qualifierInfo"
                                })
                                public static class Participant {

                                    @XmlElement(name = "QualifierInfo", required = true)
                                    protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Participant.QualifierInfo qualifierInfo;
                                    @XmlAttribute(name = "available")
                                    protected String available;
                                    @XmlAttribute(name = "minAdultAge")
                                    protected String minAdultAge;
                                    @XmlAttribute(name = "maxIndividuals")
                                    protected Integer maxIndividuals;
                                    @XmlAttribute(name = "maxChildren")
                                    protected Integer maxChildren;
                                    @XmlAttribute(name = "maxAdults")
                                    protected Integer maxAdults;
                                    @XmlAttribute(name = "maxChildAge")
                                    protected Integer maxChildAge;
                                    @XmlAttribute(name = "minChildAge")
                                    protected Integer minChildAge;
                                    @XmlAttribute(name = "maxAdultAge")
                                    protected String maxAdultAge;

                                    
                                    public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Participant.QualifierInfo getQualifierInfo() {
                                        return qualifierInfo;
                                    }

                                    
                                    public void setQualifierInfo(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.BasicInfo.TPAExtensions.ActivityTPA.Participant.QualifierInfo value) {
                                        this.qualifierInfo = value;
                                    }

                                    
                                    public String getAvailable() {
                                        return available;
                                    }

                                    
                                    public void setAvailable(String value) {
                                        this.available = value;
                                    }

                                    
                                    public String getMinAdultAge() {
                                        return minAdultAge;
                                    }

                                    
                                    public void setMinAdultAge(String value) {
                                        this.minAdultAge = value;
                                    }

                                    
                                    public Integer getMaxIndividuals() {
                                        return maxIndividuals;
                                    }

                                    
                                    public void setMaxIndividuals(Integer value) {
                                        this.maxIndividuals = value;
                                    }

                                    
                                    public Integer getMaxChildren() {
                                        return maxChildren;
                                    }

                                    
                                    public void setMaxChildren(Integer value) {
                                        this.maxChildren = value;
                                    }

                                    
                                    public Integer getMaxAdults() {
                                        return maxAdults;
                                    }

                                    
                                    public void setMaxAdults(Integer value) {
                                        this.maxAdults = value;
                                    }

                                    
                                    public Integer getMaxChildAge() {
                                        return maxChildAge;
                                    }

                                    
                                    public void setMaxChildAge(Integer value) {
                                        this.maxChildAge = value;
                                    }

                                    
                                    public Integer getMinChildAge() {
                                        return minChildAge;
                                    }

                                    
                                    public void setMinChildAge(Integer value) {
                                        this.minChildAge = value;
                                    }

                                    
                                    public String getMaxAdultAge() {
                                        return maxAdultAge;
                                    }

                                    
                                    public void setMaxAdultAge(String value) {
                                        this.maxAdultAge = value;
                                    }


                                    
                                    @XmlAccessorType(XmlAccessType.FIELD)
                                    @XmlType(name = "", propOrder = {
                                        "value"
                                    })
                                    public static class QualifierInfo {

                                        @XmlValue
                                        protected String value;
                                        @XmlAttribute(name = "Extension")
                                        protected String extension;

                                        
                                        public String getValue() {
                                            return value;
                                        }

                                        
                                        public void setValue(String value) {
                                            this.value = value;
                                        }

                                        
                                        public String getExtension() {
                                            return extension;
                                        }

                                        
                                        public void setExtension(String value) {
                                            this.extension = value;
                                        }

                                    }

                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "value"
                                })
                                public static class Questions {

                                    @XmlValue
                                    protected String value;
                                    @XmlAttribute(name = "RequiredInBook")
                                    protected String requiredInBook;

                                    
                                    public String getValue() {
                                        return value;
                                    }

                                    
                                    public void setValue(String value) {
                                        this.value = value;
                                    }

                                    
                                    public String getRequiredInBook() {
                                        return requiredInBook;
                                    }

                                    
                                    public void setRequiredInBook(String value) {
                                        this.requiredInBook = value;
                                    }

                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "value"
                                })
                                public static class ShippingDetails {

                                    @XmlValue
                                    protected String value;
                                    @XmlAttribute(name = "available")
                                    protected String available;

                                    
                                    public String getValue() {
                                        return value;
                                    }

                                    
                                    public void setValue(String value) {
                                        this.value = value;
                                    }

                                    
                                    public String getAvailable() {
                                        return available;
                                    }

                                    
                                    public void setAvailable(String value) {
                                        this.available = value;
                                    }

                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "name",
                                    "id",
                                    "reference",
                                    "rateKey"
                                })
                                public static class SupplierDetails {

                                    @XmlElement(required = true)
                                    protected String name;
                                    @XmlElement(name = "ID")
                                    protected int id;
                                    @XmlElement(name = "Reference")
                                    protected int reference;
                                    @XmlElement(name = "RateKey")
                                    protected int rateKey;
                                    @XmlAttribute(name = "available")
                                    protected String available;

                                    
                                    public String getName() {
                                        return name;
                                    }

                                    
                                    public void setName(String value) {
                                        this.name = value;
                                    }

                                    
                                    public int getID() {
                                        return id;
                                    }

                                    
                                    public void setID(int value) {
                                        this.id = value;
                                    }

                                    
                                    public int getReference() {
                                        return reference;
                                    }

                                    
                                    public void setReference(int value) {
                                        this.reference = value;
                                    }

                                    
                                    public int getRateKey() {
                                        return rateKey;
                                    }

                                    
                                    public void setRateKey(int value) {
                                        this.rateKey = value;
                                    }

                                    
                                    public String getAvailable() {
                                        return available;
                                    }

                                    
                                    public void setAvailable(String value) {
                                        this.available = value;
                                    }

                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "value"
                                })
                                public static class TimeSlots {

                                    @XmlValue
                                    protected String value;
                                    @XmlAttribute(name = "available")
                                    protected String available;

                                    
                                    public String getValue() {
                                        return value;
                                    }

                                    
                                    public void setValue(String value) {
                                        this.value = value;
                                    }

                                    
                                    public String getAvailable() {
                                        return available;
                                    }

                                    
                                    public void setAvailable(String value) {
                                        this.available = value;
                                    }

                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "value"
                                })
                                public static class TourLanguage {

                                    @XmlValue
                                    protected String value;
                                    @XmlAttribute(name = "available")
                                    protected String available;

                                    
                                    public String getValue() {
                                        return value;
                                    }

                                    
                                    public void setValue(String value) {
                                        this.value = value;
                                    }

                                    
                                    public String getAvailable() {
                                        return available;
                                    }

                                    
                                    public void setAvailable(String value) {
                                        this.available = value;
                                    }

                                }


                                
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "value"
                                })
                                public static class Vouchers {

                                    @XmlValue
                                    protected String value;
                                    @XmlAttribute(name = "available")
                                    protected String available;

                                    
                                    public String getValue() {
                                        return value;
                                    }

                                    
                                    public void setValue(String value) {
                                        this.value = value;
                                    }

                                    
                                    public String getAvailable() {
                                        return available;
                                    }

                                    
                                    public void setAvailable(String value) {
                                        this.available = value;
                                    }

                                }

                            }

                        }

                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "shortDescription",
                        "longDescription"
                    })
                    public static class Description {

                        @XmlElement(name = "ShortDescription", required = true)
                        protected String shortDescription;
                        @XmlElement(name = "LongDescription", required = true)
                        protected String longDescription;
                        @XmlAttribute(name = "available")
                        protected String available;

                        
                        public String getShortDescription() {
                            return shortDescription;
                        }

                        
                        public void setShortDescription(String value) {
                            this.shortDescription = value;
                        }

                        
                        public String getLongDescription() {
                            return longDescription;
                        }

                        
                        public void setLongDescription(String value) {
                            this.longDescription = value;
                        }

                        
                        public String getAvailable() {
                            return available;
                        }

                        
                        public void setAvailable(String value) {
                            this.available = value;
                        }

                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "value"
                    })
                    public static class Extra {

                        @XmlValue
                        protected String value;
                        @XmlAttribute(name = "available")
                        protected String available;

                        
                        public String getValue() {
                            return value;
                        }

                        
                        public void setValue(String value) {
                            this.value = value;
                        }

                        
                        public String getAvailable() {
                            return available;
                        }

                        
                        public void setAvailable(String value) {
                            this.available = value;
                        }

                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "address",
                        "region"
                    })
                    public static class Location {

                        @XmlElement(name = "Address", required = true)
                        protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location.Address address;
                        @XmlElement(name = "Region", required = true)
                        protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location.Region region;

                        
                        public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location.Address getAddress() {
                            return address;
                        }

                        
                        public void setAddress(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location.Address value) {
                            this.address = value;
                        }

                        
                        public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location.Region getRegion() {
                            return region;
                        }

                        
                        public void setRegion(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location.Region value) {
                            this.region = value;
                        }


                        
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "countryName"
                        })
                        public static class Address {

                            @XmlElement(name = "CountryName", required = true)
                            protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location.Address.CountryName countryName;

                            
                            public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location.Address.CountryName getCountryName() {
                                return countryName;
                            }

                            
                            public void setCountryName(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Location.Address.CountryName value) {
                                this.countryName = value;
                            }


                            
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "value"
                            })
                            public static class CountryName {

                                @XmlValue
                                protected String value;
                                @XmlAttribute(name = "Code")
                                protected String code;

                                
                                public String getValue() {
                                    return value;
                                }

                                
                                public void setValue(String value) {
                                    this.value = value;
                                }

                                
                                public String getCode() {
                                    return code;
                                }

                                
                                public void setCode(String value) {
                                    this.code = value;
                                }

                            }

                        }


                        
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "value"
                        })
                        public static class Region {

                            @XmlValue
                            protected String value;
                            @XmlAttribute(name = "RegionCode")
                            protected Short regionCode;

                            
                            public String getValue() {
                                return value;
                            }

                            
                            public void setValue(String value) {
                                this.value = value;
                            }

                            
                            public Short getRegionCode() {
                                return regionCode;
                            }

                            
                            public void setRegionCode(Short value) {
                                this.regionCode = value;
                            }

                        }

                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "summary",
                        "participantCategory"
                    })
                    public static class Pricing {

                        @XmlElement(name = "Summary", required = true)
                        protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.Summary summary;
                        @XmlElement(name = "ParticipantCategory")
                        protected List<SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.ParticipantCategory> participantCategory;
                        @XmlAttribute(name = "available")
                        protected String available;
                        @XmlAttribute(name = "PerPaxPriceInd")
                        protected String perPaxPriceInd;

                        
                        public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.Summary getSummary() {
                            return summary;
                        }

                        
                        public void setSummary(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.Summary value) {
                            this.summary = value;
                        }

                        
                        public List<SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.ParticipantCategory> getParticipantCategory() {
                            if (participantCategory == null) {
                                participantCategory = new ArrayList<SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.ParticipantCategory>();
                            }
                            return this.participantCategory;
                        }

                        
                        public String getAvailable() {
                            return available;
                        }

                        
                        public void setAvailable(String value) {
                            this.available = value;
                        }

                        
                        public String getPerPaxPriceInd() {
                            return perPaxPriceInd;
                        }

                        
                        public void setPerPaxPriceInd(String value) {
                            this.perPaxPriceInd = value;
                        }


                        
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "qualifierInfo",
                            "price"
                        })
                        public static class ParticipantCategory {

                            @XmlElement(name = "QualifierInfo", required = true)
                            protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.ParticipantCategory.QualifierInfo qualifierInfo;
                            @XmlElement(name = "Price", required = true)
                            protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.ParticipantCategory.Price price;

                            
                            public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.ParticipantCategory.QualifierInfo getQualifierInfo() {
                                return qualifierInfo;
                            }

                            
                            public void setQualifierInfo(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.ParticipantCategory.QualifierInfo value) {
                                this.qualifierInfo = value;
                            }

                            
                            public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.ParticipantCategory.Price getPrice() {
                                return price;
                            }

                            
                            public void setPrice(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.ParticipantCategory.Price value) {
                                this.price = value;
                            }


                            
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "value"
                            })
                            public static class Price {

                                @XmlValue
                                protected String value;
                                @XmlAttribute(name = "CurrencyCode")
                                protected String currencyCode;
                                @XmlAttribute(name = "Amount")
                                protected Float amount;
                                @XmlAttribute(name = "PriceForDate")
                                protected String priceForDate;

                                
                                public String getValue() {
                                    return value;
                                }

                                
                                public void setValue(String value) {
                                    this.value = value;
                                }

                                
                                public String getCurrencyCode() {
                                    return currencyCode;
                                }

                                
                                public void setCurrencyCode(String value) {
                                    this.currencyCode = value;
                                }

                                
                                public Float getAmount() {
                                    return amount;
                                }

                                
                                public void setAmount(Float value) {
                                    this.amount = value;
                                }

                                
                                public String getPriceForDate() {
                                    return priceForDate;
                                }

                                
                                public void setPriceForDate(String value) {
                                    this.priceForDate = value;
                                }

                            }


                            
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "value"
                            })
                            public static class QualifierInfo {

                                @XmlValue
                                protected String value;
                                @XmlAttribute(name = "Extension")
                                protected String extension;

                                
                                public String getValue() {
                                    return value;
                                }

                                
                                public void setValue(String value) {
                                    this.value = value;
                                }

                                
                                public String getExtension() {
                                    return extension;
                                }

                                
                                public void setExtension(String value) {
                                    this.extension = value;
                                }

                            }

                        }


                        
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "taxAmounts"
                        })
                        public static class Summary {

                            @XmlElement(name = "TaxAmounts", required = true)
                            protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.Summary.TaxAmounts taxAmounts;
                            @XmlAttribute(name = "Amount")
                            protected Float amount;
                            @XmlAttribute(name = "CurrencyCode")
                            protected String currencyCode;

                            
                            public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.Summary.TaxAmounts getTaxAmounts() {
                                return taxAmounts;
                            }

                            
                            public void setTaxAmounts(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Pricing.Summary.TaxAmounts value) {
                                this.taxAmounts = value;
                            }

                            
                            public Float getAmount() {
                                return amount;
                            }

                            
                            public void setAmount(Float value) {
                                this.amount = value;
                            }

                            
                            public String getCurrencyCode() {
                                return currencyCode;
                            }

                            
                            public void setCurrencyCode(String value) {
                                this.currencyCode = value;
                            }


                            
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "value"
                            })
                            public static class TaxAmounts {

                                @XmlValue
                                protected String value;
                                @XmlAttribute(name = "available")
                                protected String available;

                                
                                public String getValue() {
                                    return value;
                                }

                                
                                public void setValue(String value) {
                                    this.value = value;
                                }

                                
                                public String getAvailable() {
                                    return available;
                                }

                                
                                public void setAvailable(String value) {
                                    this.available = value;
                                }

                            }

                        }

                    }


                    
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "detail"
                    })
                    public static class Schedule {

                        @XmlElement(name = "Detail", required = true)
                        protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule.Detail detail;
                        @XmlAttribute(name = "IsDurationAvailable")
                        protected String isDurationAvailable;

                        
                        public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule.Detail getDetail() {
                            return detail;
                        }

                        
                        public void setDetail(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule.Detail value) {
                            this.detail = value;
                        }

                        
                        public String getIsDurationAvailable() {
                            return isDurationAvailable;
                        }

                        
                        public void setIsDurationAvailable(String value) {
                            this.isDurationAvailable = value;
                        }


                        
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "operationTimes"
                        })
                        public static class Detail {

                            @XmlElement(name = "OperationTimes", required = true)
                            protected SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule.Detail.OperationTimes operationTimes;
                            @XmlAttribute(name = "Start")
                            @XmlSchemaType(name = "dateTime")
                            protected String start;
                            @XmlAttribute(name = "Duration")
                            protected String duration;
                            @XmlAttribute(name = "End")
                            @XmlSchemaType(name = "dateTime")
                            protected String end;

                            
                            public SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule.Detail.OperationTimes getOperationTimes() {
                                return operationTimes;
                            }

                            
                            public void setOperationTimes(SearchRS.ResponseBody.OTATourActivityAvailRSWrapper.OTATourActivityAvailRS.TourActivityInfo.Schedule.Detail.OperationTimes value) {
                                this.operationTimes = value;
                            }

                            
                            public String getStart() {
                                return start;
                            }

                            
                            public void setStart(String value) {
                                this.start = value;
                            }

                            
                            public String getDuration() {
                                return duration;
                            }

                            
                            public void setDuration(String value) {
                                this.duration = value;
                            }

                            
                            public String getEnd() {
                                return end;
                            }

                            
                            public void setEnd(String value) {
                                this.end = value;
                            }


                            
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "value"
                            })
                            public static class OperationTimes {

                                @XmlValue
                                protected String value;
                                @XmlAttribute(name = "available")
                                protected String available;
                                @XmlAttribute(name = "IsTextFormat")
                                protected String isTextFormat;

                                
                                public String getValue() {
                                    return value;
                                }

                                
                                public void setValue(String value) {
                                    this.value = value;
                                }

                                
                                public String getAvailable() {
                                    return available;
                                }

                                
                                public void setAvailable(String value) {
                                    this.available = value;
                                }

                                
                                public String getIsTextFormat() {
                                    return isTextFormat;
                                }

                                
                                public void setIsTextFormat(String value) {
                                    this.isTextFormat = value;
                                }

                            }

                        }

                    }

                }

            }

        }

    }


    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "status",
        "userID",
        "sessionID",
        "transactionID"
    })
    public static class ResponseHeader {

        @XmlElement(name = "Status", required = true)
        protected String status;
        @XmlElement(name = "UserID", required = true)
        protected String userID;
        @XmlElement(name = "SessionID", required = true)
        protected String sessionID;
        @XmlElement(name = "TransactionID", required = true)
        protected String transactionID;

        
        public String getStatus() {
            return status;
        }

        
        public void setStatus(String value) {
            this.status = value;
        }

        
        public String getUserID() {
            return userID;
        }

        
        public void setUserID(String value) {
            this.userID = value;
        }

        
        public String getSessionID() {
            return sessionID;
        }

        
        public void setSessionID(String value) {
            this.sessionID = value;
        }

        
        public String getTransactionID() {
            return transactionID;
        }

        
        public void setTransactionID(String value) {
            this.transactionID = value;
        }

    }

}
